// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT.
//
// Static `with { type: 'text' }` imports so `bun build --compile`
// embeds every migration into the binary (runtime FS reads resolve to
// nothing inside the compiled executable). Re-run the script after
// adding or removing a migration.

import m000 from './migrations/001_core.sql' with { type: 'text' };
import m001 from './migrations/002_task_lifecycle.sql' with { type: 'text' };
import m002 from './migrations/003_projects.sql' with { type: 'text' };
import m003 from './migrations/004_clean_test_artifacts.sql' with { type: 'text' };
import m004 from './migrations/005_pg_state.sql' with { type: 'text' };
import m005 from './migrations/006_fix_agents_schema.sql' with { type: 'text' };
import m006 from './migrations/007_observability.sql' with { type: 'text' };
import m007 from './migrations/007_reconcile_mailbox_team_chat.sql' with { type: 'text' };
import m008 from './migrations/008_boards.sql' with { type: 'text' };
import m009 from './migrations/009_app_store.sql' with { type: 'text' };
import m010 from './migrations/010_runtime_events.sql' with { type: 'text' };
import m011 from './migrations/010_session_capture_v2.sql' with { type: 'text' };
import m012 from './migrations/011_data_model_v5.sql' with { type: 'text' };
import m013 from './migrations/012_executor_model.sql' with { type: 'text' };
import m014 from './migrations/013_external_linking.sql' with { type: 'text' };
import m015 from './migrations/014_comms_protocol.sql' with { type: 'text' };
import m016 from './migrations/015_agent_archived_state.sql' with { type: 'text' };
import m017 from './migrations/015_archive_lifecycle.sql' with { type: 'text' };
import m018 from './migrations/016_team_spawner.sql' with { type: 'text' };
import m019 from './migrations/017_wishes_table.sql' with { type: 'text' };
import m020 from './migrations/018_drop_app_store.sql' with { type: 'text' };
import m021 from './migrations/019_retention.sql' with { type: 'text' };
import m022 from './migrations/020_agent_metadata.sql' with { type: 'text' };
import m023 from './migrations/025_sdk_metadata_index.sql' with { type: 'text' };
import m024 from './migrations/026_executors_omni_metadata_index.sql' with { type: 'text' };
import m025 from './migrations/027_audit_events_notify.sql' with { type: 'text' };
import m026 from './migrations/028_events_trace_id.sql' with { type: 'text' };
import m027 from './migrations/029_omni_requests.sql' with { type: 'text' };
import m028 from './migrations/029_session_display_name.sql' with { type: 'text' };
import m029 from './migrations/031_mailbox_delivery_status.sql' with { type: 'text' };
import m030 from './migrations/032_approvals.sql' with { type: 'text' };
import m031 from './migrations/033_approval_request_notify.sql' with { type: 'text' };
import m032 from './migrations/034_approvals_omni_message_id.sql' with { type: 'text' };
import m033 from './migrations/035_bridge_sessions.sql' with { type: 'text' };
import m034 from './migrations/036_teams_parent_chain.sql' with { type: 'text' };
import m035 from './migrations/037_runtime_events_otel_columns.sql' with { type: 'text' };
import m036 from './migrations/038_runtime_events_partition.sql' with { type: 'text' };
import m037 from './migrations/039_runtime_events_siblings.sql' with { type: 'text' };
import m038 from './migrations/040_listen_channel_split.sql' with { type: 'text' };
import m039 from './migrations/041_rbac_roles.sql' with { type: 'text' };
import m040 from './migrations/042_executor_turn_columns.sql' with { type: 'text' };
import m041 from './migrations/043_detector_events_schema.sql' with { type: 'text' };
import m042 from './migrations/043_executor_read_role.sql' with { type: 'text' };
import m043 from './migrations/044_phase_b_flip_defaults.sql' with { type: 'text' };
import m044 from './migrations/045_fix_stringified_jsonb.sql' with { type: 'text' };
import m045 from './migrations/046_dir_agents_state_null.sql' with { type: 'text' };
import m046 from './migrations/047_drop_agents_claude_session_id.sql' with { type: 'text' };
import m047 from './migrations/048_session_sync_require_started_at.sql' with { type: 'text' };
import m048 from './migrations/049_agents_kind_generated.sql' with { type: 'text' };
import m049 from './migrations/050_archive_legacy_identity_rows.sql' with { type: 'text' };
import m050 from './migrations/051_assignments_seq.sql' with { type: 'text' };
import m051 from './migrations/053_master_backfill_and_shadow_cleanup.sql' with { type: 'text' };
import m052 from './migrations/054_fix_subagent_team_inheritance.sql' with { type: 'text' };
import m053 from './migrations/054_mailbox_source_meta.sql' with { type: 'text' };
import m054 from './migrations/055_default_auto_resume_true.sql' with { type: 'text' };
import m055 from './migrations/055_runtime_events_partition_drain.sql' with { type: 'text' };
import m056 from './migrations/056_hook_perf_baseline_view.sql' with { type: 'text' };
import m057 from './migrations/057_hook_perf_baseline_view_filter_fix.sql' with { type: 'text' };
import m058 from './migrations/058_claude_usage_view.sql' with { type: 'text' };
import m059 from './migrations/059_agent_observability_view.sql' with { type: 'text' };
import m060 from './migrations/060_agent_observability_core_view.sql' with { type: 'text' };
import m061 from './migrations/061_agents_id_invariant_and_fk_lockdown.sql' with { type: 'text' };
import m062 from './migrations/062_drop_fk_mailbox_from_worker_temp.sql' with { type: 'text' };
import m063 from './migrations/064_drain_default_uses_replica_bridge.sql' with { type: 'text' };

export interface EmbeddedMigration {
  name: string;
  sql: string;
}

/** All migrations, lexicographic order, embedded at build time. */
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
  { name: '001_core', sql: m000 },
  { name: '002_task_lifecycle', sql: m001 },
  { name: '003_projects', sql: m002 },
  { name: '004_clean_test_artifacts', sql: m003 },
  { name: '005_pg_state', sql: m004 },
  { name: '006_fix_agents_schema', sql: m005 },
  { name: '007_observability', sql: m006 },
  { name: '007_reconcile_mailbox_team_chat', sql: m007 },
  { name: '008_boards', sql: m008 },
  { name: '009_app_store', sql: m009 },
  { name: '010_runtime_events', sql: m010 },
  { name: '010_session_capture_v2', sql: m011 },
  { name: '011_data_model_v5', sql: m012 },
  { name: '012_executor_model', sql: m013 },
  { name: '013_external_linking', sql: m014 },
  { name: '014_comms_protocol', sql: m015 },
  { name: '015_agent_archived_state', sql: m016 },
  { name: '015_archive_lifecycle', sql: m017 },
  { name: '016_team_spawner', sql: m018 },
  { name: '017_wishes_table', sql: m019 },
  { name: '018_drop_app_store', sql: m020 },
  { name: '019_retention', sql: m021 },
  { name: '020_agent_metadata', sql: m022 },
  { name: '025_sdk_metadata_index', sql: m023 },
  { name: '026_executors_omni_metadata_index', sql: m024 },
  { name: '027_audit_events_notify', sql: m025 },
  { name: '028_events_trace_id', sql: m026 },
  { name: '029_omni_requests', sql: m027 },
  { name: '029_session_display_name', sql: m028 },
  { name: '031_mailbox_delivery_status', sql: m029 },
  { name: '032_approvals', sql: m030 },
  { name: '033_approval_request_notify', sql: m031 },
  { name: '034_approvals_omni_message_id', sql: m032 },
  { name: '035_bridge_sessions', sql: m033 },
  { name: '036_teams_parent_chain', sql: m034 },
  { name: '037_runtime_events_otel_columns', sql: m035 },
  { name: '038_runtime_events_partition', sql: m036 },
  { name: '039_runtime_events_siblings', sql: m037 },
  { name: '040_listen_channel_split', sql: m038 },
  { name: '041_rbac_roles', sql: m039 },
  { name: '042_executor_turn_columns', sql: m040 },
  { name: '043_detector_events_schema', sql: m041 },
  { name: '043_executor_read_role', sql: m042 },
  { name: '044_phase_b_flip_defaults', sql: m043 },
  { name: '045_fix_stringified_jsonb', sql: m044 },
  { name: '046_dir_agents_state_null', sql: m045 },
  { name: '047_drop_agents_claude_session_id', sql: m046 },
  { name: '048_session_sync_require_started_at', sql: m047 },
  { name: '049_agents_kind_generated', sql: m048 },
  { name: '050_archive_legacy_identity_rows', sql: m049 },
  { name: '051_assignments_seq', sql: m050 },
  { name: '053_master_backfill_and_shadow_cleanup', sql: m051 },
  { name: '054_fix_subagent_team_inheritance', sql: m052 },
  { name: '054_mailbox_source_meta', sql: m053 },
  { name: '055_default_auto_resume_true', sql: m054 },
  { name: '055_runtime_events_partition_drain', sql: m055 },
  { name: '056_hook_perf_baseline_view', sql: m056 },
  { name: '057_hook_perf_baseline_view_filter_fix', sql: m057 },
  { name: '058_claude_usage_view', sql: m058 },
  { name: '059_agent_observability_view', sql: m059 },
  { name: '060_agent_observability_core_view', sql: m060 },
  { name: '061_agents_id_invariant_and_fk_lockdown', sql: m061 },
  { name: '062_drop_fk_mailbox_from_worker_temp', sql: m062 },
  { name: '064_drain_default_uses_replica_bridge', sql: m063 },
];
