export default {
  id: 'genie-app',
  views: [
    {
      id: 'agents',
      label: 'Agents',
      permission: 'agents',
      minRole: 'viewer' as const,
      natsPrefix: 'agent',
      defaultSize: { width: 1200, height: 800 },
      component: './views/agents/ui/AgentsView',
      desktop: {
        icon: '/icons/dusk/users.svg',
        categories: ['System'],
        comment: 'Agent hierarchy and management',
      },
    },
    {
      id: 'tasks',
      label: 'Tasks',
      permission: 'tasks',
      minRole: 'viewer' as const,
      natsPrefix: 'task',
      defaultSize: { width: 1200, height: 800 },
      component: './views/tasks/ui/TasksView',
      desktop: {
        icon: '/icons/dusk/kanban.svg',
        categories: ['Productivity'],
        comment: 'Task kanban board',
      },
    },
    {
      id: 'terminal',
      label: 'Terminal',
      permission: 'terminal',
      minRole: 'platform-dev' as const,
      natsPrefix: 'pty',
      defaultSize: { width: 900, height: 600 },
      fullSizeContent: true,
      component: './views/terminal/ui/TerminalView',
      desktop: {
        icon: '/icons/dusk/terminal.svg',
        categories: ['System'],
        comment: 'Agent terminal sessions',
      },
    },
    {
      id: 'dashboard',
      label: 'Dashboard',
      permission: 'dashboard',
      minRole: 'viewer' as const,
      natsPrefix: 'dashboard',
      defaultSize: { width: 1200, height: 800 },
      component: './views/dashboard/ui/DashboardView',
      desktop: {
        icon: '/icons/dusk/dashboard.svg',
        categories: ['System'],
        comment: 'KPI overview',
      },
    },
    {
      id: 'wizard',
      label: 'Setup',
      permission: 'dashboard',
      minRole: 'viewer' as const,
      natsPrefix: 'wizard',
      defaultSize: { width: 600, height: 500 },
      component: './views/wizard/ui/WizardView',
      desktop: {
        icon: '/icons/dusk/wand.svg',
        categories: ['System'],
        comment: 'First-launch workspace wizard',
      },
    },
    {
      id: 'activity',
      label: 'Activity',
      permission: 'activity',
      minRole: 'viewer' as const,
      natsPrefix: 'event',
      defaultSize: { width: 900, height: 600 },
      component: './views/activity/ui/ActivityView',
      desktop: {
        icon: '/icons/dusk/activity.svg',
        categories: ['System'],
        comment: 'Real-time event feed',
      },
    },
  ],
  store: {
    name: 'Genie',
    shortDescription: 'AI agent orchestration cockpit',
    description: 'Desktop app for managing AI agent teams, tasks, and terminal sessions. Part of the Automagik Bundle.',
    category: 'AI & Automation',
    author: { name: 'Namastex Labs', verified: true },
    tags: ['agents', 'ai', 'orchestration', 'terminal', 'kanban'],
    permissions: ['nats:os.genie.*'],
  },
};
