#!/usr/bin/env bun
/**
 * Codegen: src/db/migrations.generated.ts
 *
 * `bun build --compile` only embeds modules reachable via STATIC import.
 * The old loader used readdirSync + Bun.file() on src/db/migrations/ — a
 * runtime FS read that resolves to nothing inside the compiled binary
 * (the .sql files are not bundled), so `genie db migrate` reported
 * "Applied: 0" on a completely empty database and the schema was never
 * created (blocking native genie → autopg/pgserve-v3 migration).
 *
 * This generates a manifest of static `with { type: 'text' }` imports —
 * which Bun DOES embed into the compiled binary — preserving lexicographic
 * order. Re-run after adding/removing a migration:
 *
 *   bun run scripts/gen-migrations-manifest.ts
 *
 * It is wired into `scripts/build-binary.sh` so the binary can never ship
 * a stale manifest. The generated file is committed so a plain
 * `bun build` works without the codegen step too.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const MIGRATIONS_DIR = join(import.meta.dir, '..', 'src', 'db', 'migrations');
const OUT = join(import.meta.dir, '..', 'src', 'db', 'migrations.generated.ts');

const files = readdirSync(MIGRATIONS_DIR)
  .filter((f) => f.endsWith('.sql'))
  .sort();

const idOf = (i: number) => `m${String(i).padStart(3, '0')}`;

const lines: string[] = [
  '// AUTO-GENERATED by scripts/gen-migrations-manifest.ts — DO NOT EDIT.',
  '//',
  "// Static `with { type: 'text' }` imports so `bun build --compile`",
  '// embeds every migration into the binary (runtime FS reads resolve to',
  '// nothing inside the compiled executable). Re-run the script after',
  '// adding or removing a migration.',
  '',
];

files.forEach((f, i) => {
  lines.push(`import ${idOf(i)} from './migrations/${f}' with { type: 'text' };`);
});

lines.push('');
lines.push('export interface EmbeddedMigration {');
lines.push('  name: string;');
lines.push('  sql: string;');
lines.push('}');
lines.push('');
lines.push('/** All migrations, lexicographic order, embedded at build time. */');
lines.push('export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [');
files.forEach((f, i) => {
  const name = f.replace(/\.sql$/, '');
  // Migration basenames are [A-Za-z0-9_] only — single-quote directly so
  // the generated file matches biome (single-quote) without a format pass.
  if (!/^[A-Za-z0-9_]+$/.test(name)) {
    throw new Error(`unexpected migration filename (needs escaping): ${f}`);
  }
  lines.push(`  { name: '${name}', sql: ${idOf(i)} },`);
});
lines.push('];');
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log(`gen-migrations-manifest: wrote ${files.length} migrations → ${OUT}`);
