#!/usr/bin/env bun
/**
 * Regenerate `src/lib/legacy-skills-catalog.ts` from git history.
 *
 * The catalog is how `genie update` and `genie doctor` recognise a skill
 * directory genie shipped BEFORE the install record existed: every skill name
 * that ever lived under a `skills/` directory on any ref and is no longer
 * delivered, plus every frontmatter `description` any genie skill ever shipped
 * under any name. A directory outside the current inventory whose description
 * matches is genie's own — a third party does not copy genie's description
 * verbatim — while a name-only match is only ever reported.
 *
 * Run by hand from a full clone (`git log --all` needs the whole history; a
 * shallow CI checkout would silently produce an incomplete catalog, which is
 * why this is not part of `bun run check`):
 *
 *   bun scripts/legacy-skills-catalog.ts --write
 *   bun scripts/legacy-skills-catalog.ts --check   # exits 1 when the file is stale
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const OUTPUT = join(ROOT, 'src', 'lib', 'legacy-skills-catalog.ts');
const MARKER_DIRS = ['.genie-codex-fallback-retirement'];

function git(...args: string[]): string {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 28 });
}

function parseDescription(markdown: string): string | null {
  if (!markdown.startsWith('---\n')) return null;
  const end = markdown.indexOf('\n---', 4);
  if (end === -1) return null;
  for (const line of markdown.slice(4, end).split('\n')) {
    const match = /^description:\s*(.*)$/.exec(line);
    if (!match) continue;
    let value = (match[1] as string).trim();
    if (
      value.length >= 2 &&
      ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
    ) {
      value = value.slice(1, -1);
    }
    return value.length > 0 ? value : null;
  }
  return null;
}

function currentSkillNames(): Set<string> {
  return new Set(
    readdirSync(join(ROOT, 'skills'), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name),
  );
}

/** `{ name: Set<description> }` for every skill dir on any ref that is no longer shipped. */
function collectCatalog(): Map<string, Set<string>> {
  const catalog = new Map<string, Set<string>>();
  const commits = git('log', '--all', '--pretty=format:%H', '--', 'skills/*/SKILL.md', '*/skills/*/SKILL.md')
    .split('\n')
    .filter((line) => /^[0-9a-f]{40}$/.test(line));
  const seenBlobs = new Set<string>();
  for (const commit of commits) {
    const tree = git('ls-tree', '-r', commit).split('\n');
    for (const row of tree) {
      // `(?:.*\/)?` — a root-level `skills/<name>/SKILL.md` has no leading
      // slash; anchoring on one silently skipped every skill genie ever shipped
      // from the repo root and kept only nested worktree copies.
      const match = /^\d+ blob ([0-9a-f]{40})\t(?:.*\/)?skills\/([^/]+)\/SKILL\.md$/.exec(row);
      if (!match) continue;
      const [, blob, name] = match as unknown as [string, string, string];
      if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) continue;
      const key = `${blob} ${name}`;
      if (seenBlobs.has(key)) continue;
      seenBlobs.add(key);
      const description = parseDescription(git('cat-file', 'blob', blob));
      if (description === null) continue;
      if (!catalog.has(name)) catalog.set(name, new Set());
      (catalog.get(name) as Set<string>).add(description);
    }
  }
  return catalog;
}

function render(catalog: Map<string, Set<string>>): string {
  const current = currentSkillNames();
  const names = [...catalog.keys()].filter((name) => !current.has(name)).sort();
  const descriptions = [...new Set([...catalog.values()].flatMap((set) => [...set]))].sort();
  const lines: string[] = [
    '// GENERATED by `bun scripts/legacy-skills-catalog.ts --write` from git history. Do not edit by hand.',
    '//',
    '// Every skill name genie shipped under a `skills/` directory on any ref and no',
    '// longer delivers, plus every frontmatter `description` any genie skill ever',
    '// carried under any name. A directory in an agent home that is not in the',
    "// current inventory and whose description appears here is genie's own",
    '// pre-record install (see `src/lib/legacy-skills.ts`).',
    '',
    "/** Genie-owned marker directories left by deleted runtimes; genie's by name alone. */",
    `export const LEGACY_MARKER_DIRS: readonly string[] = ${JSON.stringify(MARKER_DIRS)};`,
    '',
    '/** Skill names genie once delivered and no longer does. */',
    `export const LEGACY_SKILL_NAMES: readonly string[] = ${JSON.stringify(names)};`,
    '',
    '/** Every frontmatter `description` a genie skill ever shipped with, under any name. */',
    'export const GENIE_SKILL_DESCRIPTIONS: readonly string[] = [',
  ];
  for (const description of descriptions) lines.push(`  ${JSON.stringify(description)},`);
  lines.push('];', '');
  return lines.join('\n');
}

const mode = process.argv[2];
const rendered = render(collectCatalog());
/** The catalog is committed in the repository's biome style, so the generator emits it that way. */
function formatted(source: string): string {
  return execFileSync('bunx', ['biome', 'format', '--stdin-file-path', relative(ROOT, OUTPUT)], {
    cwd: ROOT,
    encoding: 'utf8',
    input: source,
    maxBuffer: 1 << 26,
  });
}

if (mode === '--write') {
  writeFileSync(OUTPUT, formatted(rendered), 'utf8');
  process.stdout.write(`legacy-skills-catalog: wrote ${OUTPUT}\n`);
} else if (mode === '--check') {
  let existing = '';
  try {
    existing = readFileSync(OUTPUT, 'utf8');
  } catch {
    // Missing counts as stale.
  }
  if (existing !== formatted(rendered)) {
    process.stderr.write('legacy-skills-catalog: stale — run `bun scripts/legacy-skills-catalog.ts --write`\n');
    process.exit(1);
  }
  process.stdout.write('legacy-skills-catalog: current\n');
} else {
  process.stdout.write(rendered);
}
