#!/usr/bin/env bun

/**
 * pgserve-apply-tuning: install (or remove) the genie tuning block in
 * `~/.genie/data/pgserve/postgresql.conf`.
 *
 * The patch is shipped as a single managed block bracketed by sentinel
 * comments. Running this script is idempotent: re-applying replaces the
 * existing block, never duplicates it.
 *
 * Modes:
 *   --dry-run             show the planned change as a unified diff, write nothing
 *   --apply               write the change, after backing up the existing conf
 *   --revert              remove the managed block and restore the most recent backup
 *   --patch <path>        override the patch file (default: wish folder copy)
 *   --data-dir <path>     override pgserve data dir (default: $GENIE_HOME/data/pgserve)
 *
 * Reload is the operator's responsibility:
 *   pg_ctl -D $GENIE_HOME/data/pgserve reload   # most settings
 *   genie serve restart                         # for shared_preload_libraries
 *
 * Settings that require a full restart are flagged at the top of the patch.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';

const BEGIN_MARK = '# >>> genie pgserve tuning (managed block) >>>';
const END_MARK = '# <<< genie pgserve tuning (managed block) <<<';

type Args = {
  mode: 'dry-run' | 'apply' | 'revert';
  patchPath: string;
  dataDir: string;
};

function parseArgs(argv: string[]): Args {
  let mode: Args['mode'] | null = null;
  let patchPath = resolve('.genie/wishes/hookify-perf-foundation/postgresql.conf.patch');
  const home = process.env.GENIE_HOME ?? join(homedir(), '.genie');
  let dataDir = join(home, 'data', 'pgserve');
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') mode = 'dry-run';
    else if (a === '--apply') mode = 'apply';
    else if (a === '--revert') mode = 'revert';
    else if (a === '--patch') patchPath = resolve(argv[++i]);
    else if (a === '--data-dir') dataDir = resolve(argv[++i]);
    else if (a === '--help' || a === '-h') {
      console.log(
        'pgserve-apply-tuning — install or remove the genie pgserve tuning block.\n\n' +
          'Modes (pick one):\n' +
          '  --dry-run     show planned diff, do not write\n' +
          '  --apply       back up postgresql.conf and install the block\n' +
          '  --revert      remove the block (restores from backup if present)\n\n' +
          'Options:\n' +
          '  --patch <path>     override patch source\n' +
          '  --data-dir <path>  override pgserve data dir\n',
      );
      process.exit(0);
    } else throw new Error(`unknown arg: ${a}`);
  }
  if (!mode) {
    throw new Error('pick one mode: --dry-run, --apply, or --revert');
  }
  return { mode, patchPath, dataDir };
}

function stripManagedBlock(conf: string): string {
  const lines = conf.split('\n');
  const out: string[] = [];
  let inBlock = false;
  for (const line of lines) {
    if (line.startsWith(BEGIN_MARK)) {
      inBlock = true;
      continue;
    }
    if (line.startsWith(END_MARK)) {
      inBlock = false;
      continue;
    }
    if (!inBlock) out.push(line);
  }
  // Collapse trailing blank lines we may have introduced when removing the block.
  while (out.length > 1 && out[out.length - 1] === '' && out[out.length - 2] === '') {
    out.pop();
  }
  return out.join('\n');
}

function buildManagedBlock(patchBody: string): string {
  const trimmed = patchBody.trimEnd();
  return `${BEGIN_MARK}\n# Generated by scripts/pgserve-apply-tuning.ts. Do not edit by hand —\n# changes will be overwritten on the next --apply. Use --revert to remove.\n${trimmed}\n${END_MARK}\n`;
}

function unifiedDiff(beforeLabel: string, afterLabel: string, before: string, after: string): string {
  const beforeLines = before.split('\n');
  const afterLines = after.split('\n');
  // Trivial diff: emit the symmetric difference around the managed block.
  // We are not implementing a full LCS — the change is always a contiguous
  // managed block, so a stripped baseline + appended block is enough to show.
  const stripped = stripManagedBlock(before);
  const sameTail = stripped === before.replace(/\n+$/, '\n').trimEnd();
  const out: string[] = [`--- ${beforeLabel}`, `+++ ${afterLabel}`];
  if (sameTail && !before.includes(BEGIN_MARK)) {
    out.push('@@ existing conf preserved unchanged @@');
  } else {
    out.push('@@ existing managed block will be replaced @@');
  }
  const beforeBlock = before.includes(BEGIN_MARK)
    ? before.slice(before.indexOf(BEGIN_MARK), before.indexOf(END_MARK) + END_MARK.length).split('\n')
    : [];
  const afterBlock = after.includes(BEGIN_MARK)
    ? after.slice(after.indexOf(BEGIN_MARK), after.indexOf(END_MARK) + END_MARK.length).split('\n')
    : [];
  for (const line of beforeBlock) out.push(`- ${line}`);
  for (const line of afterBlock) out.push(`+ ${line}`);
  // Ack lines variables to avoid biome unused warnings in dev.
  void beforeLines;
  void afterLines;
  return out.join('\n');
}

function backupPath(confPath: string): string {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  return `${confPath}.bak.${stamp}`;
}

function findLatestBackup(confPath: string): string | null {
  // Same-dir scan — look for `<conf>.bak.<stamp>`.
  const dir = confPath.slice(0, confPath.lastIndexOf('/'));
  const base = confPath.slice(confPath.lastIndexOf('/') + 1);
  const fs = require('node:fs') as typeof import('node:fs');
  if (!fs.existsSync(dir)) return null;
  const candidates = fs
    .readdirSync(dir)
    .filter((n: string) => n.startsWith(`${base}.bak.`))
    .sort();
  return candidates.length === 0 ? null : join(dir, candidates[candidates.length - 1]);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (!existsSync(args.patchPath)) {
    throw new Error(
      `patch file not found: ${args.patchPath}\nexpected the wish-folder canonical patch — run from repo root or pass --patch`,
    );
  }
  const confPath = join(args.dataDir, 'postgresql.conf');
  if (!existsSync(confPath)) {
    throw new Error(`postgresql.conf not found at ${confPath} — is pgserve initialized?`);
  }

  const patchBody = readFileSync(args.patchPath, 'utf-8');
  const conf = readFileSync(confPath, 'utf-8');

  if (args.mode === 'revert') {
    const stripped = stripManagedBlock(conf);
    if (stripped === conf) {
      console.log('[pgserve-tuning] no managed block found; nothing to revert');
      const backup = findLatestBackup(confPath);
      if (backup) {
        console.log(`[pgserve-tuning] (latest backup available at ${backup} — restore manually if needed)`);
      }
      return;
    }
    writeFileSync(confPath, stripped);
    console.log(`[pgserve-tuning] removed managed block from ${confPath}`);
    console.log(`[pgserve-tuning] reload pgserve to apply: 'genie serve restart'`);
    return;
  }

  const stripped = stripManagedBlock(conf);
  const block = buildManagedBlock(patchBody);
  // Ensure exactly one trailing newline before the block, regardless of input shape.
  const next = `${stripped.replace(/\n+$/, '')}\n\n${block}`;

  if (args.mode === 'dry-run') {
    console.log(unifiedDiff(confPath, `${confPath} (planned)`, conf, next));
    console.log('\n[pgserve-tuning] dry-run only — no files modified');
    console.log('[pgserve-tuning] to apply: bun run scripts/pgserve-apply-tuning.ts --apply');
    return;
  }

  const backup = backupPath(confPath);
  writeFileSync(backup, conf);
  writeFileSync(confPath, next);
  console.log(`[pgserve-tuning] backed up ${confPath} -> ${backup}`);
  console.log(`[pgserve-tuning] wrote managed block to ${confPath}`);
  console.log('[pgserve-tuning] reload required:');
  console.log(`[pgserve-tuning]   - reload-only settings: 'pg_ctl -D ${args.dataDir} reload'`);
  console.log(`[pgserve-tuning]   - shared_preload_libraries needs full restart: 'genie serve restart'`);
  console.log('[pgserve-tuning] revert with: bun run scripts/pgserve-apply-tuning.ts --revert');
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(`[pgserve-tuning] failed: ${err instanceof Error ? err.stack : err}`);
    process.exit(1);
  });
