import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import * as readline from 'node:readline';

// Generate tmux.conf snippet for Warp-like shortcuts
function generateTmuxConfig(): string {
  return `# Warp-like keyboard shortcuts (generated by genie-cli)
# To use: add to ~/.tmux.conf or source this file

# Ctrl+T: New window (tab) in current session
bind-key -n C-t new-window -c "#{pane_current_path}"

# Ctrl+S: Vertical split (requires stty -ixon in shell rc)
bind-key -n C-s split-window -v -c "#{pane_current_path}"

# Ctrl+Shift+S: Horizontal split
bind-key -n C-S split-window -h -c "#{pane_current_path}"
`;
}

// Generate termux.properties snippet for extra keys
function generateTermuxConfig(): string {
  return `# Warp-like extra keys (generated by genie-cli)
# To use: add to ~/.termux/termux.properties

# Extra keys row with F-keys for shortcuts
# F1=New Tab, F2=VSplit, F3=HSplit
extra-keys = [['ESC','TAB','CTRL','ALT','F1','F2','F3']]
`;
}

// Generate shell functions for bashrc/zshrc
function generateShellFunctions(): string {
  return `# Warp-like shortcuts (generated by genie-cli)
# To use: add to ~/.bashrc or ~/.zshrc

# Disable Ctrl+S flow control (required for Ctrl+S to work in tmux)
stty -ixon 2>/dev/null

# Genie shortcuts (for Termux extra keys F1-F3)
genie-new-tab() {
  local session
  session=$(tmux display-message -p '#S' 2>/dev/null)
  if [ -n "$session" ]; then
    tmux new-window -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-vsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -v -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-hsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -h -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

# Bind F1-F3 to genie shortcuts (works in Termux)
bind -x '"\eOP":"genie-new-tab"' 2>/dev/null   # F1
bind -x '"\eOQ":"genie-vsplit"' 2>/dev/null    # F2
bind -x '"\eOR":"genie-hsplit"' 2>/dev/null    # F3
`;
}

// Display all shortcuts in a readable format
export function displayShortcuts(): void {
  console.log(`
Warp-like Terminal Shortcuts for tmux + Termux

┌──────────────────┬────────────────────────────────────────┐
│ Shortcut         │ Action                                 │
├──────────────────┼────────────────────────────────────────┤
│ Ctrl+T           │ New tab (window) in current session    │
│ Ctrl+S           │ Vertical split in current session      │
│ Ctrl+Shift+S     │ Horizontal split in current session    │
└──────────────────┴────────────────────────────────────────┘

Termux Extra Keys (F1-F3):
  F1 → New tab       F2 → Vertical split
  F3 → Horizontal split

Commands:
  genie shortcuts --tmux     Output tmux.conf snippet
  genie shortcuts --termux   Output termux.properties snippet
  genie shortcuts --install  Install to config files
`);
}

// Helper to prompt user
async function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim().toLowerCase());
    });
  });
}

// Check if content already exists in file
function contentExists(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, 'utf-8');
  return content.includes(marker);
}

/**
 * Prompt to install config content to a file. Skips if marker already present.
 */
async function promptInstallTo(
  filePath: string,
  marker: string,
  label: string,
  contentFn: () => string,
  ensureDir?: string,
): Promise<void> {
  if (contentExists(filePath, marker)) {
    console.log(`✓ ${label} already has genie shortcuts`);
    return;
  }
  const answer = await prompt(`Add shortcuts to ${filePath}? [Y/n] `);
  if (answer === 'n') {
    console.log(`⏭️ Skipped ${label}`);
    return;
  }
  if (ensureDir && !existsSync(ensureDir)) {
    mkdirSync(ensureDir, { recursive: true });
  }
  appendFileSync(filePath, `\n${contentFn()}`);
  console.log(`✅ Added to ${filePath}`);
}

// Install shortcuts to config files
export async function installShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Installing Warp-like shortcuts...\n');

  await promptInstallTo(join(home, '.tmux.conf'), marker, 'tmux.conf', generateTmuxConfig);

  const shellRc = existsSync(join(home, '.zshrc')) ? join(home, '.zshrc') : join(home, '.bashrc');
  await promptInstallTo(shellRc, marker, shellRc, generateShellFunctions);

  const termuxDir = join(home, '.termux');
  const termuxProps = join(termuxDir, 'termux.properties');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    await promptInstallTo(termuxProps, marker, 'termux.properties', generateTermuxConfig, termuxDir);
    if (contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  console.log('\n✅ Installation complete!');
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}

// Check if shortcuts are installed in a file
export function isShortcutsInstalled(filePath: string): boolean {
  const marker = 'generated by genie-cli';
  return contentExists(filePath, marker);
}

const GENIE_CONTENT_MARKERS = [
  'genie',
  'Ctrl+',
  'split-window',
  'new-window',
  'stty -ixon',
  'Warp-like',
  'bind-key -n',
  'extra-keys',
  'F1=',
  'bind -x',
];

/**
 * Check if a line is part of genie-generated config content.
 */
function isGenieContentLine(line: string, prevLine?: string): boolean {
  if (GENIE_CONTENT_MARKERS.some((m) => line.includes(m))) return true;
  return line.startsWith('#') && prevLine !== undefined && prevLine.includes('genie');
}

/**
 * Check if this line ends a genie marked block.
 * Returns true if the line is the end boundary (blank line before non-genie content).
 */
function isBlockEndBoundary(line: string, nextLine: string | undefined): boolean {
  return line.trim() === '' && nextLine !== undefined && !nextLine.includes('genie');
}

/**
 * Process a single line inside a genie content block.
 * Returns 'skip' to continue skipping, 'end-skip' to end block without keeping line,
 * or 'end-keep' to end block and keep the line.
 */
function processBlockLine(
  line: string,
  prevLine: string | undefined,
  nextLine: string | undefined,
): 'skip' | 'end-skip' | 'end-keep' {
  if (isBlockEndBoundary(line, nextLine)) return 'end-skip';
  if (!isGenieContentLine(line, prevLine) && line.trim() !== '') return 'end-keep';
  return 'skip';
}

/**
 * Strip trailing blank lines from an array in-place.
 */
function stripTrailingBlanks(arr: string[]): void {
  while (arr.length > 0 && arr[arr.length - 1].trim() === '') arr.pop();
}

/**
 * Filter lines by removing genie-generated content blocks delimited by markers.
 */
function filterMarkedLines(lines: string[], marker: string): string[] {
  const result: string[] = [];
  let inBlock = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!inBlock && line.includes(marker)) {
      inBlock = true;
      stripTrailingBlanks(result);
      continue;
    }
    if (!inBlock) {
      result.push(line);
      continue;
    }
    const action = processBlockLine(line, lines[i - 1], lines[i + 1]);
    if (action === 'end-keep') {
      inBlock = false;
      result.push(line);
    } else if (action === 'end-skip') {
      inBlock = false;
    }
  }

  stripTrailingBlanks(result);
  return result;
}

// Remove content between markers from a file
function removeMarkedContent(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, 'utf-8');
  if (!content.includes(marker)) return false;

  const filtered = filterMarkedLines(content.split('\n'), marker);
  const newContent = filtered.length > 0 ? `${filtered.join('\n')}\n` : '';
  writeFileSync(filePath, newContent);
  return true;
}

/**
 * Prompt to uninstall config content from a file. Skips if marker not present.
 */
async function promptUninstallFrom(filePath: string, marker: string, label: string): Promise<void> {
  if (!existsSync(filePath)) return;
  if (!contentExists(filePath, marker)) {
    console.log(`✓ ${label} has no genie shortcuts`);
    return;
  }
  const answer = await prompt(`Remove shortcuts from ${filePath}? [Y/n] `);
  if (answer === 'n') {
    console.log(`⏭️ Skipped ${label}`);
    return;
  }
  if (removeMarkedContent(filePath, marker)) {
    console.log(`✅ Removed from ${filePath}`);
  }
}

// Uninstall shortcuts from config files
export async function uninstallShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Uninstalling Warp-like shortcuts...\n');

  await promptUninstallFrom(join(home, '.tmux.conf'), marker, 'tmux.conf');

  for (const shellRc of [join(home, '.zshrc'), join(home, '.bashrc')]) {
    await promptUninstallFrom(shellRc, marker, shellRc);
  }

  const termuxDir = join(home, '.termux');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    const termuxProps = join(termuxDir, 'termux.properties');
    await promptUninstallFrom(termuxProps, marker, 'termux.properties');
    if (!contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  console.log('\n✅ Uninstallation complete!');
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}
