#!/usr/bin/env bash
# batch-commit.sh — Optimized commit for metrics updates
# Auto-generated by generate-tools.py
# Idempotent: safe to run multiple times, regenerate freely.
#
# Usage: bash batch-commit.sh <metrics.json> <repo-root> <state-file>
#
# Optimizations:
# - Single git add for all files
# - Pre-formatted commit message (no subshell)
# - Skip if working tree is clean

set -euo pipefail

METRICS_FILE="${1:?Usage: batch-commit.sh <metrics.json> <repo-root> <state-file>}"
REPO_ROOT="${2:?}"
STATE_FILE="${3:?}"

cd "$REPO_ROOT"

# Skip if no changes
if git diff --quiet HEAD -- README.md "$STATE_FILE" 2>/dev/null; then
  echo "No changes to commit" >&2
  exit 2
fi

# Read metrics for commit message
releases=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('releases_per_day', 0))")
avg_time=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('avg_bugfix_time_hours', 0))")
ship_rate=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('ship_rate_pct', 0))")

COMMIT_MSG="chore: update live metrics (${releases}/day, ${avg_time}h avg, ${ship_rate}% SHIP)"

# Single add + commit
git add README.md "$STATE_FILE"
git commit -m "$COMMIT_MSG"

echo "$COMMIT_MSG"
