#!/usr/bin/env bash
# cached-fetch.sh — Cached GitHub API fetcher with TTL
# Auto-generated by generate-tools.py
# Idempotent: safe to run multiple times, regenerate freely.
#
# Usage: source cached-fetch.sh; cached_gh_api <endpoint> [ttl_seconds]
# Default TTL: 1800s (30 minutes) — daily agent runs don't need real-time data

CACHE_DIR="${GENIE_METRICS_CACHE:-/tmp/metrics-updater-cache}"
DEFAULT_TTL="${GENIE_METRICS_CACHE_TTL:-1800}"

mkdir -p "$CACHE_DIR"

cached_gh_api() {
  local endpoint="$1"
  local ttl="${2:-$DEFAULT_TTL}"
  local cache_key
  cache_key=$(echo "$endpoint" | md5sum | cut -d' ' -f1)
  local cache_file="$CACHE_DIR/${cache_key}.json"
  local meta_file="$CACHE_DIR/${cache_key}.meta"

  # Check cache validity
  if [[ -f "$cache_file" && -f "$meta_file" ]]; then
    local cached_at
    cached_at=$(cat "$meta_file" 2>/dev/null || echo 0)
    local now
    now=$(date +%s)
    local age=$((now - cached_at))

    if (( age < ttl )); then
      echo "[cache] HIT: $endpoint (age=${age}s, ttl=${ttl}s)" >&2
      cat "$cache_file"
      return 0
    fi
    echo "[cache] STALE: $endpoint (age=${age}s, ttl=${ttl}s)" >&2
  else
    echo "[cache] MISS: $endpoint" >&2
  fi

  # Fetch fresh data
  local response
  if response=$(gh api "$endpoint" --paginate 2>/dev/null); then
    echo "$response" > "$cache_file"
    date +%s > "$meta_file"
    echo "$response"
    return 0
  fi

  # Fallback to stale cache
  if [[ -f "$cache_file" ]]; then
    echo "[cache] FALLBACK: Using stale cache for $endpoint" >&2
    cat "$cache_file"
    return 0
  fi

  echo "[cache] FAIL: No data for $endpoint" >&2
  return 1
}

# Warm cache for common endpoints (call at start of run)
warm_cache() {
  local owner="${1:-automagik-dev}"
  local repo="${2:-genie}"
  echo "[cache] Warming cache for $owner/$repo..." >&2
  cached_gh_api "repos/$owner/$repo/releases" >/dev/null 2>&1 &
  cached_gh_api "repos/$owner/$repo/pulls?state=closed&sort=updated&direction=desc&per_page=100" >/dev/null 2>&1 &
  wait
  echo "[cache] Cache warmed" >&2
}

# Clear expired cache entries
clean_cache() {
  local max_age="${1:-86400}"  # Default: 24h
  local now
  now=$(date +%s)
  for meta in "$CACHE_DIR"/*.meta; do
    [[ -f "$meta" ]] || continue
    local cached_at
    cached_at=$(cat "$meta" 2>/dev/null || echo 0)
    if (( now - cached_at > max_age )); then
      local base="${meta%.meta}"
      rm -f "$base.json" "$meta"
      echo "[cache] Cleaned: $(basename "$base")" >&2
    fi
  done
}
