#!/usr/bin/env bash
# commit-formatter.sh — Clean commit message formatter for metrics updates
# Auto-generated by metrics-updater agent (v1, 2026-03-24)
# This tool will be refined by the agent over time.

set -euo pipefail

# Usage: commit-formatter.sh <metrics_json_file>
# Reads metrics JSON and outputs a formatted commit message.
#
# Input JSON format:
# {
#   "releases_per_day": 27,
#   "avg_bugfix_time_hours": 2.4,
#   "ship_rate_pct": 100,
#   "parallel_agents": 5,
#   "updated": "2026-03-24"
# }

METRICS_FILE="${1:-}"

if [[ -z "$METRICS_FILE" || ! -f "$METRICS_FILE" ]]; then
  echo "Usage: commit-formatter.sh <metrics.json>" >&2
  exit 1
fi

# Extract values
releases=$(jq -r '.releases_per_day // 0' "$METRICS_FILE")
avg_time=$(jq -r '.avg_bugfix_time_hours // 0' "$METRICS_FILE")
ship_rate=$(jq -r '.ship_rate_pct // 0' "$METRICS_FILE")
agents=$(jq -r '.parallel_agents // 0' "$METRICS_FILE")

# Format commit message
echo "chore: update live metrics (${releases}/day, ${avg_time}h avg, ${ship_rate}% SHIP)"
