#!/usr/bin/env bash
# commit-formatter.sh — Clean commit message formatter for metrics updates
# Auto-generated by metrics-updater agent (v1, 2026-03-24)
# Updated: v2 — includes LoC/commits/PRs in commit message

set -euo pipefail

# Usage: commit-formatter.sh <metrics_json_file>
# Reads metrics JSON and outputs a formatted commit message.

METRICS_FILE="${1:-}"

if [[ -z "$METRICS_FILE" || ! -f "$METRICS_FILE" ]]; then
  echo "Usage: commit-formatter.sh <metrics.json>" >&2
  exit 1
fi

# Extract values
releases=$(jq -r '.releases_per_day // 0' "$METRICS_FILE")
avg_time=$(jq -r '.avg_bugfix_time_hours // 0' "$METRICS_FILE")
ship_rate=$(jq -r '.ship_rate_pct // 0' "$METRICS_FILE")
loc=$(jq -r '.loc_changed_24h // 0' "$METRICS_FILE")
commits=$(jq -r '.commits_24h // 0' "$METRICS_FILE")
prs=$(jq -r '.prs_24h // 0' "$METRICS_FILE")

# Format commit message
echo "chore: update live metrics (${releases}/day, ${avg_time}h avg, ${ship_rate}% SHIP, ${loc} LoC, ${commits} commits, ${prs} PRs)"
