#!/usr/bin/env python3
"""generate-tools.py — Analyze performance data and generate/update optimization tools.

Reads runs.jsonl, identifies slow operations, and generates shell/Python helpers
in the tools/ directory. Tools are idempotent — safe to run multiple times.

Usage:
    python3 generate-tools.py [--runs-file <path>] [--tools-dir <path>] [--dry-run]

Generated tools:
    - cached-fetch.sh: GitHub API response cache with TTL-based invalidation
    - fast-parse.py: Optimized metrics parser with pre-compiled patterns
    - batch-commit.sh: Batched git operations for faster commits
"""

import json
import sys
import os
import stat
import argparse
from datetime import datetime, timezone
from pathlib import Path
from collections import defaultdict


def load_runs(runs_file: str) -> list[dict]:
    """Load all runs from JSONL file."""
    runs = []
    path = Path(runs_file)
    if not path.exists():
        return runs
    for line in path.read_text().strip().split('\n'):
        if line.strip():
            try:
                runs.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return runs


def identify_slow_steps(runs: list[dict], threshold_ms: int = 500) -> list[dict]:
    """Identify steps that consistently exceed the threshold."""
    step_stats = defaultdict(list)
    for run in runs:
        for step in run.get('steps', []):
            step_stats[step['name']].append(step['duration_ms'])

    slow_steps = []
    for name, durations in step_stats.items():
        avg = sum(durations) / len(durations)
        if avg >= threshold_ms:
            slow_steps.append({
                'name': name,
                'avg_ms': round(avg, 1),
                'max_ms': max(durations),
                'samples': len(durations),
            })

    slow_steps.sort(key=lambda s: s['avg_ms'], reverse=True)
    return slow_steps


def generate_cached_fetch(tools_dir: Path) -> bool:
    """Generate cached-fetch.sh — wraps gh API with disk cache + TTL."""
    target = tools_dir / 'cached-fetch.sh'

    content = '''#!/usr/bin/env bash
# cached-fetch.sh — Cached GitHub API fetcher with TTL
# Auto-generated by generate-tools.py
# Idempotent: safe to run multiple times, regenerate freely.
#
# Usage: source cached-fetch.sh; cached_gh_api <endpoint> [ttl_seconds]
# Default TTL: 1800s (30 minutes) — daily agent runs don't need real-time data

CACHE_DIR="${GENIE_METRICS_CACHE:-/tmp/metrics-updater-cache}"
DEFAULT_TTL="${GENIE_METRICS_CACHE_TTL:-1800}"

mkdir -p "$CACHE_DIR"

cached_gh_api() {
  local endpoint="$1"
  local ttl="${2:-$DEFAULT_TTL}"
  local cache_key
  cache_key=$(echo "$endpoint" | md5sum | cut -d\' \' -f1)
  local cache_file="$CACHE_DIR/${cache_key}.json"
  local meta_file="$CACHE_DIR/${cache_key}.meta"

  # Check cache validity
  if [[ -f "$cache_file" && -f "$meta_file" ]]; then
    local cached_at
    cached_at=$(cat "$meta_file" 2>/dev/null || echo 0)
    local now
    now=$(date +%s)
    local age=$((now - cached_at))

    if (( age < ttl )); then
      echo "[cache] HIT: $endpoint (age=${age}s, ttl=${ttl}s)" >&2
      cat "$cache_file"
      return 0
    fi
    echo "[cache] STALE: $endpoint (age=${age}s, ttl=${ttl}s)" >&2
  else
    echo "[cache] MISS: $endpoint" >&2
  fi

  # Fetch fresh data
  local response
  if response=$(gh api "$endpoint" --paginate 2>/dev/null); then
    echo "$response" > "$cache_file"
    date +%s > "$meta_file"
    echo "$response"
    return 0
  fi

  # Fallback to stale cache
  if [[ -f "$cache_file" ]]; then
    echo "[cache] FALLBACK: Using stale cache for $endpoint" >&2
    cat "$cache_file"
    return 0
  fi

  echo "[cache] FAIL: No data for $endpoint" >&2
  return 1
}

# Warm cache for common endpoints (call at start of run)
warm_cache() {
  local owner="${1:-automagik-dev}"
  local repo="${2:-genie}"
  echo "[cache] Warming cache for $owner/$repo..." >&2
  cached_gh_api "repos/$owner/$repo/releases" >/dev/null 2>&1 &
  cached_gh_api "repos/$owner/$repo/pulls?state=closed&sort=updated&direction=desc&per_page=100" >/dev/null 2>&1 &
  wait
  echo "[cache] Cache warmed" >&2
}

# Clear expired cache entries
clean_cache() {
  local max_age="${1:-86400}"  # Default: 24h
  local now
  now=$(date +%s)
  for meta in "$CACHE_DIR"/*.meta; do
    [[ -f "$meta" ]] || continue
    local cached_at
    cached_at=$(cat "$meta" 2>/dev/null || echo 0)
    if (( now - cached_at > max_age )); then
      local base="${meta%.meta}"
      rm -f "$base.json" "$meta"
      echo "[cache] Cleaned: $(basename "$base")" >&2
    fi
  done
}
'''

    target.write_text(content)
    make_executable(target)
    return True


def generate_fast_parse(tools_dir: Path) -> bool:
    """Generate fast-parse.py — optimized metrics parser."""
    target = tools_dir / 'fast-parse.py'

    content = '''#!/usr/bin/env python3
"""fast-parse.py — Optimized metrics parser with pre-compiled patterns.

Auto-generated by generate-tools.py.
Idempotent: safe to run multiple times, regenerate freely.

Differences from parse-metrics.py:
- Pre-compiled datetime parsing (avoids repeated fromisoformat)
- Batch processing (single pass over PR data)
- Early termination (stops counting when past cutoff)

Usage:
    python3 fast-parse.py --releases <file> --prs <file> --agents <N> [-o output.json]
"""

import json
import sys
import argparse
from datetime import datetime, timedelta, timezone
from functools import lru_cache

NOW = datetime.now(timezone.utc)
CUTOFF_24H = NOW - timedelta(hours=24)
CUTOFF_7D = NOW - timedelta(days=7)


def parse_iso(s: str) -> datetime:
    """Fast ISO8601 parsing."""
    return datetime.fromisoformat(s.replace('Z', '+00:00'))


def compute_all_metrics(releases: list, prs: list, parallel_agents: int) -> dict:
    """Single-pass computation of all metrics from raw API data."""
    # Releases in last 24h
    releases_24h = sum(1 for r in releases if parse_iso(r['created_at']) >= CUTOFF_24H)

    # PR metrics in single pass
    merge_durations = []
    total_merged_7d = 0
    shipped_first = 0

    for pr in prs:
        merged_at = pr.get('merged_at')
        if not merged_at:
            continue
        merged = parse_iso(merged_at)
        if merged < CUTOFF_7D:
            continue  # Past our window — skip

        total_merged_7d += 1
        created = parse_iso(pr['created_at'])
        merge_durations.append((merged - created).total_seconds() / 3600)
        shipped_first += 1  # v1: all merged = shipped

    avg_merge = round(sum(merge_durations) / len(merge_durations), 1) if merge_durations else 0.0
    ship_rate = round((shipped_first / total_merged_7d) * 100, 0) if total_merged_7d > 0 else 100.0

    return {
        'releases_per_day': releases_24h,
        'avg_bugfix_time_hours': avg_merge,
        'ship_rate_pct': ship_rate,
        'parallel_agents': parallel_agents,
        'updated': NOW.strftime('%Y-%m-%d'),
    }


def main():
    parser = argparse.ArgumentParser(description='Fast metrics parser')
    parser.add_argument('--releases', required=True, help='Releases JSON file')
    parser.add_argument('--prs', required=True, help='PRs JSON file')
    parser.add_argument('--agents', type=int, default=0, help='Parallel agents count')
    parser.add_argument('--output', '-o', help='Output file (default: stdout)')

    args = parser.parse_args()

    with open(args.releases) as f:
        releases = json.load(f)
    with open(args.prs) as f:
        prs = json.load(f)

    metrics = compute_all_metrics(releases, prs, args.agents)
    output = json.dumps(metrics, indent=2)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(output + '\\n')
    else:
        print(output)


if __name__ == '__main__':
    main()
'''

    target.write_text(content)
    make_executable(target)
    return True


def generate_batch_commit(tools_dir: Path) -> bool:
    """Generate batch-commit.sh — batched git operations for faster commits."""
    target = tools_dir / 'batch-commit.sh'

    content = '''#!/usr/bin/env bash
# batch-commit.sh — Optimized commit for metrics updates
# Auto-generated by generate-tools.py
# Idempotent: safe to run multiple times, regenerate freely.
#
# Usage: bash batch-commit.sh <metrics.json> <repo-root> <state-file>
#
# Optimizations:
# - Single git add for all files
# - Pre-formatted commit message (no subshell)
# - Skip if working tree is clean

set -euo pipefail

METRICS_FILE="${1:?Usage: batch-commit.sh <metrics.json> <repo-root> <state-file>}"
REPO_ROOT="${2:?}"
STATE_FILE="${3:?}"

cd "$REPO_ROOT"

# Skip if no changes
if git diff --quiet HEAD -- README.md "$STATE_FILE" 2>/dev/null; then
  echo "No changes to commit" >&2
  exit 2
fi

# Read metrics for commit message
releases=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('releases_per_day', 0))")
avg_time=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('avg_bugfix_time_hours', 0))")
ship_rate=$(python3 -c "import json; print(json.load(open('$METRICS_FILE')).get('ship_rate_pct', 0))")

COMMIT_MSG="chore: update live metrics (${releases}/day, ${avg_time}h avg, ${ship_rate}% SHIP)"

# Single add + commit
git add README.md "$STATE_FILE"
git commit -m "$COMMIT_MSG"

echo "$COMMIT_MSG"
'''

    target.write_text(content)
    make_executable(target)
    return True


def make_executable(path: Path):
    """Make a file executable."""
    st = os.stat(path)
    os.chmod(path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def update_runs_log(runs_file: str, tools_generated: int):
    """Update the last run entry with tools_generated count."""
    path = Path(runs_file)
    if not path.exists():
        return

    lines = path.read_text().strip().split('\n')
    if not lines:
        return

    try:
        last_run = json.loads(lines[-1])
        last_run['tools_generated'] = tools_generated
        lines[-1] = json.dumps(last_run)
        path.write_text('\n'.join(lines) + '\n')
    except (json.JSONDecodeError, IndexError):
        pass


def main():
    parser = argparse.ArgumentParser(description='Generate optimization tools from perf data')
    parser.add_argument('--runs-file', default=None, help='Path to runs.jsonl')
    parser.add_argument('--tools-dir', default=None, help='Path to tools directory')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be generated')
    parser.add_argument('--force', action='store_true', help='Regenerate all tools')

    args = parser.parse_args()

    # Auto-detect paths
    script_dir = Path(__file__).parent
    agent_dir = script_dir.parent

    if not args.runs_file:
        args.runs_file = str(agent_dir / 'state' / 'runs.jsonl')
    if not args.tools_dir:
        args.tools_dir = str(script_dir)

    tools_dir = Path(args.tools_dir)
    runs = load_runs(args.runs_file)

    if not runs:
        print('No runs found — generating baseline tools', file=sys.stderr)

    slow_steps = identify_slow_steps(runs, threshold_ms=200)

    print(f'Analyzing {len(runs)} runs...', file=sys.stderr)
    if slow_steps:
        print('Slow steps identified:', file=sys.stderr)
        for step in slow_steps:
            print(f'  {step["name"]}: avg={step["avg_ms"]}ms', file=sys.stderr)

    # Determine which tools to generate
    tools_to_generate = []
    generated_count = 0

    # Always generate cached-fetch if any fetch step is slow or on first run
    has_slow_fetch = any('fetch' in s['name'] for s in slow_steps)
    cached_fetch_exists = (tools_dir / 'cached-fetch.sh').exists()
    if has_slow_fetch or not cached_fetch_exists or args.force:
        tools_to_generate.append(('cached-fetch.sh', generate_cached_fetch, 'Cached GitHub API fetcher'))

    # Generate fast parser if parse step is slow
    has_slow_parse = any('parse' in s['name'] for s in slow_steps)
    fast_parse_exists = (tools_dir / 'fast-parse.py').exists()
    if has_slow_parse or not fast_parse_exists or args.force:
        tools_to_generate.append(('fast-parse.py', generate_fast_parse, 'Optimized metrics parser'))

    # Generate batch commit if commit step is slow
    has_slow_commit = any('commit' in s['name'] for s in slow_steps)
    batch_commit_exists = (tools_dir / 'batch-commit.sh').exists()
    if has_slow_commit or not batch_commit_exists or args.force:
        tools_to_generate.append(('batch-commit.sh', generate_batch_commit, 'Batched git commit'))

    # Generate tools
    for name, generator, description in tools_to_generate:
        if args.dry_run:
            print(f'[DRY RUN] Would generate: {name} — {description}')
        else:
            print(f'Generating: {name} — {description}', file=sys.stderr)
            if generator(tools_dir):
                generated_count += 1
                print(f'  Created: {tools_dir / name}', file=sys.stderr)

    # Update runs.jsonl with tools_generated count
    if generated_count > 0 and not args.dry_run:
        update_runs_log(args.runs_file, generated_count)
        print(f'\nGenerated {generated_count} tools', file=sys.stderr)
    elif not args.dry_run:
        print('No new tools needed', file=sys.stderr)

    # Output summary
    summary = {
        'generated': generated_count,
        'tools': [t[0] for t in tools_to_generate] if not args.dry_run else [],
        'slow_steps': slow_steps,
        'timestamp': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    }
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
