#!/usr/bin/env bash
# github-api.sh — GitHub API wrapper with caching and retry
# Auto-generated by metrics-updater agent (v1, 2026-03-24)
# This tool will be refined by the agent over time.

set -euo pipefail

OWNER="automagik-dev"
REPO="genie"
CACHE_DIR="${GENIE_METRICS_CACHE:-/tmp/metrics-updater-cache}"
CACHE_TTL="${GENIE_METRICS_CACHE_TTL:-3600}" # 1 hour default
MAX_RETRIES=3
RETRY_DELAY=2

mkdir -p "$CACHE_DIR"

# Usage: github_api <endpoint> [jq_filter]
# Example: github_api "repos/$OWNER/$REPO/releases" '.[] | .tag_name'
github_api() {
  local endpoint="$1"
  local jq_filter="${2:-.}"
  local cache_key
  cache_key=$(echo "$endpoint" | md5sum | cut -d' ' -f1)
  local cache_file="$CACHE_DIR/$cache_key.json"

  # Check cache
  if [[ -f "$cache_file" ]]; then
    local cache_age
    cache_age=$(( $(date +%s) - $(stat -c %Y "$cache_file" 2>/dev/null || echo 0) ))
    if (( cache_age < CACHE_TTL )); then
      jq "$jq_filter" "$cache_file" 2>/dev/null
      return 0
    fi
  fi

  # Fetch with retry
  local attempt=0
  local response
  while (( attempt < MAX_RETRIES )); do
    if response=$(gh api "$endpoint" --paginate 2>/dev/null); then
      echo "$response" > "$cache_file"
      echo "$response" | jq "$jq_filter" 2>/dev/null
      return 0
    fi
    attempt=$((attempt + 1))
    sleep "$RETRY_DELAY"
  done

  # Fallback: return cached data even if stale
  if [[ -f "$cache_file" ]]; then
    echo "[WARN] API failed, using stale cache for $endpoint" >&2
    jq "$jq_filter" "$cache_file" 2>/dev/null
    return 0
  fi

  echo "[ERROR] API failed and no cache available for $endpoint" >&2
  return 1
}

# Fetch releases in last 24h
fetch_releases_24h() {
  local since
  since=$(date -u -d '24 hours ago' '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date -u -v-24H '+%Y-%m-%dT%H:%M:%SZ')
  github_api "repos/$OWNER/$REPO/releases" \
    "[.[] | select(.created_at >= \"$since\")] | length"
}

# Fetch closed PRs in last 7 days
fetch_closed_prs_7d() {
  local since
  since=$(date -u -d '7 days ago' '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || date -u -v-7d '+%Y-%m-%dT%H:%M:%SZ')
  github_api "repos/$OWNER/$REPO/pulls?state=closed&sort=updated&direction=desc&per_page=100" \
    "[.[] | select(.merged_at != null and .merged_at >= \"$since\")]"
}

# Calculate average PR merge time (hours) from JSON array of PRs
calc_avg_merge_time() {
  local prs="$1"
  echo "$prs" | jq '
    [.[] |
      (.merged_at | fromdateiso8601) - (.created_at | fromdateiso8601)
    ] | if length > 0 then (add / length / 3600 * 10 | round / 10) else 0 end
  '
}

# Main: dispatch subcommand
case "${1:-help}" in
  releases)    fetch_releases_24h ;;
  prs)         fetch_closed_prs_7d ;;
  merge-time)  calc_avg_merge_time "$(fetch_closed_prs_7d)" ;;
  cache-clear) rm -rf "$CACHE_DIR"/* && echo "Cache cleared" ;;
  *)
    echo "Usage: github-api.sh {releases|prs|merge-time|cache-clear}"
    echo "  releases    - Count releases in last 24h"
    echo "  prs         - Fetch closed/merged PRs in last 7 days"
    echo "  merge-time  - Calculate average PR merge time (hours)"
    echo "  cache-clear - Clear API response cache"
    ;;
esac
