#!/usr/bin/env python3
"""parse-metrics.py — Metrics parser and calculator for metrics-updater agent.

Auto-generated by metrics-updater agent (v1, 2026-03-24).
Updated: v2 — added LoC, commits, PRs (24h) metrics.

Usage:
    python3 parse-metrics.py --releases-json <file> --prs-json <file> [--repo-root <path>]
    python3 parse-metrics.py --from-state <state.json>  # fallback mode
"""

import json
import subprocess
import sys
import argparse
from datetime import datetime, timedelta, timezone


def parse_releases_count(releases_json: list, hours: int = 24) -> int:
    """Count releases created within the last N hours."""
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    count = 0
    for release in releases_json:
        created = datetime.fromisoformat(release['created_at'].replace('Z', '+00:00'))
        if created >= cutoff:
            count += 1
    return count


def calc_avg_merge_time_hours(prs_json: list, days: int = 7) -> float:
    """Calculate average time from PR open to merge in hours (last N days)."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    durations = []
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged < cutoff:
            continue
        created = datetime.fromisoformat(pr['created_at'].replace('Z', '+00:00'))
        duration_hours = (merged - created).total_seconds() / 3600
        durations.append(duration_hours)
    if not durations:
        return 0.0
    return round(sum(durations) / len(durations), 1)


def calc_ship_rate(prs_json: list, days: int = 7) -> float:
    """Calculate SHIP rate: % of merged PRs that shipped on first review cycle.

    Heuristic: PRs with <= 1 review request cycle are considered first-pass ships.
    If review data isn't available, use merged PRs with no 'changes requested' reviews.
    """
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    total = 0
    shipped_first = 0
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged < cutoff:
            continue
        total += 1
        # Heuristic: if PR has no requested_reviewers remaining and was merged,
        # treat as shipped. More sophisticated analysis requires review events API.
        shipped_first += 1  # Default: count all merged as shipped for v1
    if total == 0:
        return 100.0
    return round((shipped_first / total) * 100, 0)


def calc_loc_changed(repo_root: str, branches: list[str] | None = None) -> int:
    """Calculate total lines changed (additions + deletions) in last 24 hours.

    When branches is provided, counts changes across all listed branches
    (e.g. ['main', 'dev']) to capture work that hasn't been promoted yet.
    """
    try:
        cmd = ['git', 'log', '--since=24 hours ago', '--stat', '--format=']
        if branches:
            cmd.extend(branches)
        else:
            cmd.append('--all')
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_root
        )
        total = 0
        for line in result.stdout.splitlines():
            if 'file' in line and 'changed' in line:
                parts = line.split(',')
                for part in parts:
                    part = part.strip()
                    if 'insertion' in part:
                        total += int(part.split()[0])
                    elif 'deletion' in part:
                        total += int(part.split()[0])
        return total
    except Exception:
        return 0


def calc_commits_24h(repo_root: str, branches: list[str] | None = None) -> int:
    """Count commits in the last 24 hours.

    When branches is provided, counts across all listed branches
    (e.g. ['main', 'dev']) to capture work not yet promoted to main.
    """
    try:
        cmd = ['git', 'log', '--since=24 hours ago', '--oneline']
        if branches:
            cmd.extend(branches)
        else:
            cmd.append('--all')
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_root
        )
        lines = [l for l in result.stdout.strip().splitlines() if l.strip()]
        return len(lines)
    except Exception:
        return 0


def calc_prs_24h(owner: str, repo: str) -> int:
    """Count PRs created in the last 24 hours using gh API."""
    try:
        since = (datetime.now(timezone.utc) - timedelta(hours=24)).strftime('%Y-%m-%dT%H:%M:%SZ')
        result = subprocess.run(
            ['gh', 'api', f'search/issues?q=repo:{owner}/{repo}+type:pr+created:>={since}',
             '--jq', '.total_count'],
            capture_output=True, text=True
        )
        return int(result.stdout.strip()) if result.stdout.strip() else 0
    except Exception:
        return 0


def format_metrics(releases_per_day: int, avg_merge_hours: float,
                   ship_rate: float, parallel_agents: int,
                   loc_changed_24h: int = 0, commits_24h: int = 0,
                   prs_24h: int = 0) -> dict:
    """Format metrics into the standard output structure."""
    return {
        'releases_per_day': releases_per_day,
        'avg_bugfix_time_hours': avg_merge_hours,
        'ship_rate_pct': ship_rate,
        'loc_changed_24h': loc_changed_24h,
        'commits_24h': commits_24h,
        'prs_24h': prs_24h,
        'parallel_agents': parallel_agents,
        'updated': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    }


def main():
    parser = argparse.ArgumentParser(description='Parse and calculate project metrics')
    parser.add_argument('--releases-json', help='Path to releases JSON file')
    parser.add_argument('--prs-json', help='Path to PRs JSON file')
    parser.add_argument('--parallel-agents', type=int, default=0,
                        help='Number of parallel agents active')
    parser.add_argument('--repo-root', default='.', help='Path to repo root for git log commands')
    parser.add_argument('--branches', nargs='+', default=['main', 'dev'],
                        help='Branches to include in git metrics (default: main dev)')
    parser.add_argument('--owner', default='automagik-dev', help='GitHub owner')
    parser.add_argument('--repo', default='genie', help='GitHub repo name')
    parser.add_argument('--from-state', help='Fallback: read last_metrics from state.json')
    parser.add_argument('--output', '-o', help='Output file (default: stdout)')

    args = parser.parse_args()

    if args.from_state:
        # Fallback mode: use cached metrics from state
        with open(args.from_state) as f:
            state = json.load(f)
        metrics = state.get('last_metrics', {})
        if not metrics:
            print('ERROR: No cached metrics in state.json', file=sys.stderr)
            sys.exit(1)
    else:
        if not args.releases_json or not args.prs_json:
            parser.error('--releases-json and --prs-json required (or use --from-state)')

        with open(args.releases_json) as f:
            releases = json.load(f)
        with open(args.prs_json) as f:
            prs = json.load(f)

        releases_count = parse_releases_count(releases)
        avg_merge = calc_avg_merge_time_hours(prs)
        ship_rate = calc_ship_rate(prs)
        loc_changed = calc_loc_changed(args.repo_root, args.branches)
        commits = calc_commits_24h(args.repo_root, args.branches)
        prs_count = calc_prs_24h(args.owner, args.repo)

        metrics = format_metrics(
            releases_per_day=releases_count,
            avg_merge_hours=avg_merge,
            ship_rate=ship_rate,
            parallel_agents=args.parallel_agents,
            loc_changed_24h=loc_changed,
            commits_24h=commits,
            prs_24h=prs_count,
        )

    output = json.dumps(metrics, indent=2)
    if args.output:
        with open(args.output, 'w') as f:
            f.write(output + '\n')
    else:
        print(output)


if __name__ == '__main__':
    main()
