#!/usr/bin/env python3
"""parse-metrics.py — Metrics parser and calculator for metrics-updater agent.

Auto-generated by metrics-updater agent (v1, 2026-03-24).
Updated: v2 — added LoC, commits, PRs (24h) metrics.

Usage:
    python3 parse-metrics.py --releases-json <file> --prs-json <file> [--repo-root <path>]
    python3 parse-metrics.py --from-state <state.json>  # fallback mode
"""

import json
import subprocess
import sys
import argparse
from datetime import datetime, timedelta, timezone


def parse_releases_count(releases_json: list, hours: int = 24) -> int:
    """Count releases created within the last N hours."""
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    count = 0
    for release in releases_json:
        created = datetime.fromisoformat(release['created_at'].replace('Z', '+00:00'))
        if created >= cutoff:
            count += 1
    return count


def calc_avg_merge_time_hours(prs_json: list, days: int = 7) -> float:
    """Calculate average time from PR open to merge in hours (last N days)."""
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    durations = []
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged < cutoff:
            continue
        created = datetime.fromisoformat(pr['created_at'].replace('Z', '+00:00'))
        duration_hours = (merged - created).total_seconds() / 3600
        durations.append(duration_hours)
    if not durations:
        return 0.0
    return round(sum(durations) / len(durations), 1)


def calc_ship_rate(prs_json: list, days: int = 7) -> float:
    """Calculate SHIP rate: % of merged PRs that shipped on first review cycle.

    Heuristic: PRs with <= 1 review request cycle are considered first-pass ships.
    If review data isn't available, use merged PRs with no 'changes requested' reviews.
    """
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    total = 0
    shipped_first = 0
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged < cutoff:
            continue
        total += 1
        # Heuristic: if PR has no requested_reviewers remaining and was merged,
        # treat as shipped. More sophisticated analysis requires review events API.
        shipped_first += 1  # Default: count all merged as shipped for v1
    if total == 0:
        return 100.0
    return round((shipped_first / total) * 100, 0)


def calc_loc_changed(repo_root: str, branches: list[str] | None = None, hours: int = 24) -> int:
    """Calculate total lines changed (additions + deletions) in last N hours.

    When branches is provided, counts changes across all listed branches
    (e.g. ['main', 'dev']) to capture work that hasn't been promoted yet.
    """
    try:
        cmd = ['git', 'log', f'--since={hours} hours ago', '--stat', '--format=']
        if branches:
            cmd.extend(branches)
        else:
            cmd.append('--all')
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_root
        )
        total = 0
        for line in result.stdout.splitlines():
            if 'file' in line and 'changed' in line:
                parts = line.split(',')
                for part in parts:
                    part = part.strip()
                    if 'insertion' in part:
                        total += int(part.split()[0])
                    elif 'deletion' in part:
                        total += int(part.split()[0])
        return total
    except Exception:
        return 0


def calc_commits_24h(repo_root: str, branches: list[str] | None = None, hours: int = 24) -> int:
    """Count commits in the last N hours.

    When branches is provided, counts across all listed branches
    (e.g. ['main', 'dev']) to capture work not yet promoted to main.
    """
    try:
        cmd = ['git', 'log', f'--since={hours} hours ago', '--oneline']
        if branches:
            cmd.extend(branches)
        else:
            cmd.append('--all')
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_root
        )
        lines = [l for l in result.stdout.strip().splitlines() if l.strip()]
        return len(lines)
    except Exception:
        return 0


def calc_files_changed(repo_root: str, hours: int = 24, branches: list[str] | None = None) -> int:
    """Count files changed in the last N hours."""
    try:
        cmd = ['git', 'log', f'--since={hours} hours ago', '--stat', '--format=']
        if branches:
            cmd.extend(branches)
        else:
            cmd.append('--all')
        result = subprocess.run(
            cmd, capture_output=True, text=True, cwd=repo_root
        )
        total = 0
        for line in result.stdout.splitlines():
            if 'file' in line and 'changed' in line:
                total += int(line.strip().split()[0])
        return total
    except Exception:
        return 0


def calc_npm_releases(package: str, hours: int = 24) -> int:
    """Count npm releases in the last N hours."""
    try:
        result = subprocess.run(
            ['npm', 'view', package, 'time', '--json'],
            capture_output=True, text=True
        )
        if not result.stdout.strip():
            return 0
        data = json.loads(result.stdout)
        cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
        count = 0
        for ver, ts in data.items():
            if ver in ('created', 'modified'):
                continue
            dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
            if dt >= cutoff:
                count += 1
        return count
    except Exception:
        return 0


def calc_merged_prs(prs_json: list, hours: int = 24) -> int:
    """Count merged PRs within the last N hours."""
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    count = 0
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged >= cutoff:
            count += 1
    return count


def calc_avg_merge_time_window(prs_json: list, hours: int = 24) -> float:
    """Calculate average merge time in hours for PRs merged in the last N hours."""
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    durations = []
    for pr in prs_json:
        if not pr.get('merged_at'):
            continue
        merged = datetime.fromisoformat(pr['merged_at'].replace('Z', '+00:00'))
        if merged < cutoff:
            continue
        created = datetime.fromisoformat(pr['created_at'].replace('Z', '+00:00'))
        durations.append((merged - created).total_seconds() / 3600)
    if not durations:
        return 0.0
    return round(sum(durations) / len(durations), 1)


def format_metrics(*, commits_7d: int = 0, loc_7d: int = 0, files_7d: int = 0,
                   prs_7d: int = 0, releases_7d: int = 0, avg_merge_7d: float = 0,
                   commits_24h: int = 0, loc_24h: int = 0, files_24h: int = 0,
                   prs_24h: int = 0, releases_24h: int = 0, avg_merge_24h: float = 0,
                   parallel_agents: int = 0) -> dict:
    """Format metrics into the standard output structure."""
    return {
        'commits_7d': commits_7d,
        'loc_changed_7d': loc_7d,
        'files_changed_7d': files_7d,
        'prs_7d': prs_7d,
        'releases_7d': releases_7d,
        'avg_merge_time_7d': avg_merge_7d,
        'commits_24h': commits_24h,
        'loc_changed_24h': loc_24h,
        'files_changed_24h': files_24h,
        'prs_24h': prs_24h,
        'releases_24h': releases_24h,
        'avg_merge_time_24h': avg_merge_24h,
        'parallel_agents': parallel_agents,
        'updated': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    }


def main():
    parser = argparse.ArgumentParser(description='Parse and calculate project metrics')
    parser.add_argument('--releases-json', help='Path to releases JSON file')
    parser.add_argument('--prs-json', help='Path to PRs JSON file')
    parser.add_argument('--parallel-agents', type=int, default=0,
                        help='Number of parallel agents active')
    parser.add_argument('--repo-root', default='.', help='Path to repo root for git log commands')
    parser.add_argument('--branches', nargs='+', default=['main', 'dev'],
                        help='Branches to include in git metrics (default: main dev)')
    parser.add_argument('--owner', default='automagik-dev', help='GitHub owner')
    parser.add_argument('--repo', default='genie', help='GitHub repo name')
    parser.add_argument('--from-state', help='Fallback: read last_metrics from state.json')
    parser.add_argument('--output', '-o', help='Output file (default: stdout)')

    args = parser.parse_args()

    if args.from_state:
        # Fallback mode: use cached metrics from state
        with open(args.from_state) as f:
            state = json.load(f)
        metrics = state.get('last_metrics', {})
        if not metrics:
            print('ERROR: No cached metrics in state.json', file=sys.stderr)
            sys.exit(1)
    else:
        if not args.releases_json or not args.prs_json:
            parser.error('--releases-json and --prs-json required (or use --from-state)')

        with open(args.releases_json) as f:
            releases = json.load(f)
        with open(args.prs_json) as f:
            prs = json.load(f)

        pkg = f'@{args.owner}/{args.repo}'

        metrics = format_metrics(
            # 7-day metrics
            commits_7d=calc_commits_24h(args.repo_root, args.branches, hours=168),
            loc_7d=calc_loc_changed(args.repo_root, args.branches, hours=168),
            files_7d=calc_files_changed(args.repo_root, hours=168, branches=args.branches),
            prs_7d=calc_merged_prs(prs, hours=168),
            releases_7d=calc_npm_releases(pkg, hours=168),
            avg_merge_7d=calc_avg_merge_time_window(prs, hours=168),
            # 24h metrics
            commits_24h=calc_commits_24h(args.repo_root, args.branches),
            loc_24h=calc_loc_changed(args.repo_root, args.branches),
            files_24h=calc_files_changed(args.repo_root, branches=args.branches),
            prs_24h=calc_merged_prs(prs),
            releases_24h=calc_npm_releases(pkg),
            avg_merge_24h=calc_avg_merge_time_window(prs),
            parallel_agents=args.parallel_agents,
        )

    output = json.dumps(metrics, indent=2)
    if args.output:
        with open(args.output, 'w') as f:
            f.write(output + '\n')
    else:
        print(output)


if __name__ == '__main__':
    main()
