#!/usr/bin/env python3
"""update-readme.py — Update README.md metrics table between signature markers.

Auto-generated by metrics-updater agent (v1, 2026-03-24).
Updated: v2 — ISO timestamp signature, 7 metric rows, no Updated column.

Usage:
    python3 update-readme.py --metrics <metrics.json> --readme <README.md>
    python3 update-readme.py --metrics <metrics.json>  # defaults to README.md in repo root
"""

import json
import re
import sys
import argparse
from datetime import datetime, timezone
from pathlib import Path

START_MARKER_PREFIX = '<!-- METRICS:START'
END_MARKER = '<!-- METRICS:END \u2014 \U0001f9de automagik/genie -->'


def build_metrics_table(metrics: dict) -> str:
    """Build the markdown metrics table with signature markers."""
    timestamp = metrics.get('updated', datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'))
    date_str = timestamp[:10] if 'T' in timestamp else timestamp

    # 7-day metrics
    commits_7d = metrics.get('commits_7d', 0)
    loc_7d = metrics.get('loc_changed_7d', 0)
    files_7d = metrics.get('files_changed_7d', 0)
    prs_7d = metrics.get('prs_7d', 0)
    releases_7d = metrics.get('releases_7d', 0)
    avg_merge_7d = metrics.get('avg_merge_time_7d', 0)

    # 24h metrics
    commits_24h = metrics.get('commits_24h', 0)
    loc_24h = metrics.get('loc_changed_24h', 0)
    files_24h = metrics.get('files_changed_24h', 0)
    prs_24h = metrics.get('prs_24h', 0)
    releases_24h = metrics.get('releases_24h', metrics.get('releases_per_day', 0))
    avg_merge_24h = metrics.get('avg_merge_time_24h', metrics.get('avg_bugfix_time_hours', 0))

    start_marker = f'<!-- METRICS:START \u2014 Updated by Genie Metrics Agent at {timestamp} -->'

    lines = [
        start_marker,
        '<p align="center">',
        '',
        '| Metric | 7 days | 24h |',
        '|--------|--------|-----|',
        f'| Commits | {commits_7d:,} | {commits_24h} |',
        f'| Lines changed | {loc_7d:,} | {loc_24h:,} |',
        f'| Files touched | {files_7d:,} | {files_24h} |',
        f'| Merged PRs | {prs_7d} | {prs_24h} |',
        f'| npm releases | {releases_7d} | {releases_24h} |',
        f'| Avg merge time | {avg_merge_7d}h | {avg_merge_24h}h |',
        '',
        f'*Last updated: {date_str}*',
        '</p>',
        END_MARKER,
    ]
    return '\n'.join(lines)


def update_readme(readme_path: str, metrics: dict) -> bool:
    """Update README.md metrics table. Returns True if content changed."""
    path = Path(readme_path)
    content = path.read_text()

    new_table = build_metrics_table(metrics)

    # Check if markers exist (match any START marker variant)
    if START_MARKER_PREFIX in content and ('<!-- METRICS:END' in content):
        # Replace existing block (match old or new marker formats)
        pattern = re.compile(
            r'<!-- METRICS:START[^\n]*-->.*?<!-- METRICS:END[^\n]*-->',
            re.DOTALL,
        )
        new_content = pattern.sub(new_table, content)
    else:
        # Insert before "## What is Genie?" heading
        anchor = '## What is Genie?'
        if anchor in content:
            new_content = content.replace(anchor, new_table + '\n\n' + anchor)
        else:
            # Fallback: append before first ## heading
            match = re.search(r'^## ', content, re.MULTILINE)
            if match:
                pos = match.start()
                new_content = content[:pos] + new_table + '\n\n' + content[pos:]
            else:
                print('ERROR: Cannot find insertion point in README', file=sys.stderr)
                return False

    if new_content == content:
        print('No changes to README (metrics unchanged)')
        return False

    path.write_text(new_content)
    print(f'README updated with metrics at {readme_path}')
    return True


def main():
    parser = argparse.ArgumentParser(description='Update README.md metrics table')
    parser.add_argument('--metrics', required=True, help='Path to metrics JSON file')
    parser.add_argument('--readme', default='README.md', help='Path to README.md')

    args = parser.parse_args()

    with open(args.metrics) as f:
        metrics = json.load(f)

    changed = update_readme(args.readme, metrics)
    sys.exit(0 if changed else 2)  # exit 2 = no changes (not an error)


if __name__ == '__main__':
    main()
