#!/usr/bin/env python3
"""update-readme.py — Update README.md metrics table between sentinel markers.

Auto-generated by metrics-updater agent (v1, 2026-03-24).

Usage:
    python3 update-readme.py --metrics <metrics.json> --readme <README.md>
    python3 update-readme.py --metrics <metrics.json>  # defaults to README.md in repo root
"""

import json
import re
import sys
import argparse
from pathlib import Path

START_MARKER = '<!-- METRICS:START -->'
END_MARKER = '<!-- METRICS:END -->'


def build_metrics_table(metrics: dict) -> str:
    """Build the markdown metrics table from metrics dict."""
    updated = metrics.get('updated', 'N/A')
    releases = metrics.get('releases_per_day', 0)
    avg_time = metrics.get('avg_bugfix_time_hours', 0)
    ship_rate = metrics.get('ship_rate_pct', 0)
    agents = metrics.get('parallel_agents', 0)

    lines = [
        START_MARKER,
        '',
        '| Metric | Value | Updated |',
        '|--------|-------|---------|',
        f'| Releases/day | **{releases}** | {updated} |',
        f'| Avg bug-fix time | **{avg_time}h** | {updated} |',
        f'| SHIP rate | **{ship_rate}%** | {updated} |',
        f'| Parallel agents | **{agents}** | {updated} |',
        '',
        END_MARKER,
    ]
    return '\n'.join(lines)


def update_readme(readme_path: str, metrics: dict) -> bool:
    """Update README.md metrics table. Returns True if content changed."""
    path = Path(readme_path)
    content = path.read_text()

    new_table = build_metrics_table(metrics)

    # Check if markers exist
    if START_MARKER in content and END_MARKER in content:
        # Replace existing block
        pattern = re.compile(
            re.escape(START_MARKER) + r'.*?' + re.escape(END_MARKER),
            re.DOTALL,
        )
        new_content = pattern.sub(new_table, content)
    else:
        # Insert before "## What is Genie?" heading
        anchor = '## What is Genie?'
        if anchor in content:
            new_content = content.replace(anchor, new_table + '\n\n' + anchor)
        else:
            # Fallback: append before first ## heading
            match = re.search(r'^## ', content, re.MULTILINE)
            if match:
                pos = match.start()
                new_content = content[:pos] + new_table + '\n\n' + content[pos:]
            else:
                print('ERROR: Cannot find insertion point in README', file=sys.stderr)
                return False

    if new_content == content:
        print('No changes to README (metrics unchanged)')
        return False

    path.write_text(new_content)
    print(f'README updated with metrics at {readme_path}')
    return True


def main():
    parser = argparse.ArgumentParser(description='Update README.md metrics table')
    parser.add_argument('--metrics', required=True, help='Path to metrics JSON file')
    parser.add_argument('--readme', default='README.md', help='Path to README.md')

    args = parser.parse_args()

    with open(args.metrics) as f:
        metrics = json.load(f)

    changed = update_readme(args.readme, metrics)
    sys.exit(0 if changed else 2)  # exit 2 = no changes (not an error)


if __name__ == '__main__':
    main()
