import { describe, expect, test } from 'bun:test';
import { displayShortcuts, isShortcutsInstalled } from './shortcuts.js';

describe('displayShortcuts', () => {
  test('does not throw', () => {
    expect(() => displayShortcuts()).not.toThrow();
  });
});

describe('isShortcutsInstalled', () => {
  test('returns false for non-existent file', () => {
    expect(isShortcutsInstalled('/tmp/nonexistent-file-12345')).toBe(false);
  });

  test('returns false for file without genie marker', () => {
    const { writeFileSync } = require('node:fs');
    const path = `/tmp/shortcuts-test-${Date.now()}.txt`;
    writeFileSync(path, 'some content without markers\n');
    expect(isShortcutsInstalled(path)).toBe(false);
    require('node:fs').unlinkSync(path);
  });

  test('returns true for file with genie marker', () => {
    const { writeFileSync } = require('node:fs');
    const path = `/tmp/shortcuts-test-${Date.now()}.txt`;
    writeFileSync(path, '# generated by genie-cli\nbind-key stuff\n');
    expect(isShortcutsInstalled(path)).toBe(true);
    require('node:fs').unlinkSync(path);
  });
});
