import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { appendFileSync, existsSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expectedSnippetLines, removeMarkedContent } from './shortcuts.js';

const CLI = join(import.meta.dir, '..', 'genie.ts');
const MARKER = 'generated by genie-cli';

let dir: string;

/** Simulate exactly what `shortcuts install` appends: `\n` + the snippet. */
function simulateInstall(filePath: string): void {
  const snippet = expectedSnippetLines(filePath);
  if (snippet === null) throw new Error(`unmanaged file: ${filePath}`);
  appendFileSync(filePath, `\n${snippet.join('\n')}`);
}

function tmuxConf(): string {
  return join(dir, '.tmux.conf');
}

function zshrc(): string {
  return join(dir, '.zshrc');
}

function runShortcuts(args: string[], input: string): { code: number; stdout: string; stderr: string } {
  // Feed answers through a shell pipe: Bun.spawnSync's `input` delivers EOF to
  // the child's readline before any `line` event (Bun 1.3.9 quirk), but shell
  // pipes deliver both lines reliably.
  const stdinSource = input === '' ? '</dev/null' : `printf '%b' ${JSON.stringify(input)} |`;
  const cmd = `${stdinSource} ${JSON.stringify(process.execPath)} ${JSON.stringify(realpathSync(CLI))} shortcuts ${args.join(' ')}`;
  const res = Bun.spawnSync(['/bin/sh', '-c', cmd], {
    stdout: 'pipe',
    stderr: 'pipe',
    env: { ...process.env, HOME: dir, PATH: '/usr/bin:/bin' },
  });
  return { code: res.exitCode, stdout: res.stdout.toString(), stderr: res.stderr.toString() };
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'genie-shortcuts-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('removeMarkedContent', () => {
  test('removes exactly the installed block and restores the original file', () => {
    writeFileSync(tmuxConf(), 'set -g prefix C-a\n');
    const original = readFileSync(tmuxConf(), 'utf-8');
    simulateInstall(tmuxConf());

    const result = removeMarkedContent(tmuxConf(), MARKER);

    expect(result).toBe('removed');
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe(original);
  });

  test('restores a .zshrc with pre-existing content byte-for-byte', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\nalias g=git\n');
    const original = readFileSync(zshrc(), 'utf-8');
    simulateInstall(zshrc());

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
  });

  test('leaves an empty file empty after the round-trip', () => {
    writeFileSync(tmuxConf(), '');
    simulateInstall(tmuxConf());

    expect(removeMarkedContent(tmuxConf(), MARKER)).toBe('removed');
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe('');
  });

  test('preserves user lines that merely contain words like genie or stty -ixon', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    // User content AFTER the block, containing genie-adjacent words.
    appendFileSync(zshrc(), '\n# my personal genie wrapper\ngenie() { command genie "$@"; }\nalias xon="stty -ixon"\n');

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    const after = readFileSync(zshrc(), 'utf-8');
    expect(after).toContain('# my personal genie wrapper');
    expect(after).toContain('genie() { command genie "$@"; }');
    expect(after).toContain('alias xon="stty -ixon"');
    expect(after).not.toContain('genie-new-tab');
    expect(after).not.toContain('bind -x');
  });

  test("returns 'modified' and leaves the file untouched when the block was edited", () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    const path = zshrc();
    const edited = readFileSync(path, 'utf-8').replace('stty -ixon 2>/dev/null', 'stty -ixon');
    writeFileSync(path, edited);

    expect(removeMarkedContent(path, MARKER)).toBe('modified');
    expect(readFileSync(path, 'utf-8')).toBe(edited);
  });

  test("returns 'absent' for files without the marker or outside the managed set", () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('absent');

    writeFileSync(join(dir, 'custom.conf'), '# generated by genie-cli\n');
    expect(removeMarkedContent(join(dir, 'custom.conf'), MARKER)).toBe('absent');
  });

  test('is idempotent: a second removal is a no-op', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    const afterFirst = readFileSync(zshrc(), 'utf-8');
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('absent');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(afterFirst);
  });
});

describe('shortcuts CLI round-trip', () => {
  test('install then uninstall restores rc files byte-for-byte', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\nalias g=git\n');
    const original = readFileSync(zshrc(), 'utf-8');

    const installed = runShortcuts(['install'], 'y\ny\n');
    expect(installed.code).toBe(0);
    expect(existsSync(tmuxConf())).toBe(true);
    expect(readFileSync(zshrc(), 'utf-8')).not.toBe(original);

    const uninstalled = runShortcuts(['uninstall'], 'y\ny\n');
    expect(uninstalled.code).toBe(0);
    expect(uninstalled.stdout).toContain('✅ Uninstallation complete!');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe('');
  });

  test('a second uninstall is a no-op and says so', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    runShortcuts(['install'], 'y\ny\n');
    const first = runShortcuts(['uninstall'], 'y\ny\n');
    expect(first.stdout).toContain('✅ Uninstallation complete!');
    const zshAfterFirst = readFileSync(zshrc(), 'utf-8');

    const second = runShortcuts(['uninstall'], 'y\ny\n');
    expect(second.code).toBe(0);
    expect(second.stdout).toContain('has no genie shortcuts');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(zshAfterFirst);
  });

  test('declining with n leaves files untouched', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    const original = readFileSync(zshrc(), 'utf-8');

    runShortcuts(['install'], 'n\nn\n');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
    expect(existsSync(tmuxConf())).toBe(false);
  });

  test('EOF on stdin does not hang and installs nothing', () => {
    const res = runShortcuts(['install'], '');
    expect(res.code).toBe(0);
    expect(existsSync(tmuxConf())).toBe(false);
    expect(existsSync(zshrc())).toBe(false);
  });
});
