import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { appendFileSync, existsSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  SHORTCUTS_NON_INTERACTIVE_MESSAGE,
  SHORTCUTS_UNANSWERED_MESSAGE,
  expectedSnippetLines,
  removeMarkedContent,
} from './shortcuts.js';

const CLI = join(import.meta.dir, '..', 'genie.ts');
const MARKER = 'generated by genie-cli';

let dir: string;

/**
 * Simulate exactly what a PRE-FENCE `shortcuts install` appended: `\n` + the
 * bare snippet. Exercises the legacy uninstall lane that existing installs
 * from those releases still depend on.
 */
function simulateInstall(filePath: string): void {
  const snippet = expectedSnippetLines(filePath);
  if (snippet === null) throw new Error(`unmanaged file: ${filePath}`);
  appendFileSync(filePath, `\n${snippet.join('\n')}`);
}

function tmuxConf(): string {
  return join(dir, '.tmux.conf');
}

function zshrc(): string {
  return join(dir, '.zshrc');
}

function runShortcuts(args: string[], input: string): { code: number; stdout: string; stderr: string } {
  // Feed answers through a shell pipe: Bun.spawnSync's `input` delivers EOF to
  // the child's readline before any `line` event (Bun 1.3.9 quirk), but shell
  // pipes deliver both lines reliably.
  const stdinSource = input === '' ? '</dev/null' : `printf '%b' ${JSON.stringify(input)} |`;
  const cmd = `${stdinSource} ${JSON.stringify(process.execPath)} ${JSON.stringify(realpathSync(CLI))} ${args.join(' ')}`;
  const res = Bun.spawnSync(['/bin/sh', '-c', cmd], {
    stdout: 'pipe',
    stderr: 'pipe',
    timeout: 20_000,
    env: { ...process.env, HOME: dir, PATH: '/usr/bin:/bin' },
  });
  return { code: res.exitCode, stdout: res.stdout.toString(), stderr: res.stderr.toString() };
}

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'genie-shortcuts-'));
});

afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

describe('removeMarkedContent', () => {
  test('removes exactly the installed block and restores the original file', () => {
    writeFileSync(tmuxConf(), 'set -g prefix C-a\n');
    const original = readFileSync(tmuxConf(), 'utf-8');
    simulateInstall(tmuxConf());

    const result = removeMarkedContent(tmuxConf(), MARKER);

    expect(result).toBe('removed');
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe(original);
  });

  test('restores a .zshrc with pre-existing content byte-for-byte', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\nalias g=git\n');
    const original = readFileSync(zshrc(), 'utf-8');
    simulateInstall(zshrc());

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
  });

  test('leaves an empty file empty after the round-trip', () => {
    writeFileSync(tmuxConf(), '');
    simulateInstall(tmuxConf());

    expect(removeMarkedContent(tmuxConf(), MARKER)).toBe('removed');
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe('');
  });

  test('preserves user lines that merely contain words like genie or stty -ixon', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    // User content AFTER the block, containing genie-adjacent words.
    appendFileSync(zshrc(), '\n# my personal genie wrapper\ngenie() { command genie "$@"; }\nalias xon="stty -ixon"\n');

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    const after = readFileSync(zshrc(), 'utf-8');
    expect(after).toContain('# my personal genie wrapper');
    expect(after).toContain('genie() { command genie "$@"; }');
    expect(after).toContain('alias xon="stty -ixon"');
    expect(after).not.toContain('genie-new-tab');
    expect(after).not.toContain('bind -x');
  });

  test("returns 'modified' and leaves the file untouched when the block was edited", () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    const path = zshrc();
    const edited = readFileSync(path, 'utf-8').replace('stty -ixon 2>/dev/null', 'stty -ixon');
    writeFileSync(path, edited);

    expect(removeMarkedContent(path, MARKER)).toBe('modified');
    expect(readFileSync(path, 'utf-8')).toBe(edited);
  });

  test("returns 'absent' for files without the marker or outside the managed set", () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('absent');

    writeFileSync(join(dir, 'custom.conf'), '# generated by genie-cli\n');
    expect(removeMarkedContent(join(dir, 'custom.conf'), MARKER)).toBe('absent');
  });

  test('is idempotent: a second removal is a no-op', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    const afterFirst = readFileSync(zshrc(), 'utf-8');
    expect(removeMarkedContent(zshrc(), MARKER)).toBe('absent');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(afterFirst);
  });

  test('preserves user-owned trailing blank lines after the block', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    simulateInstall(zshrc());
    // User appended content AFTER the block, deliberately ending in blank lines.
    appendFileSync(zshrc(), '\nalias g=git\n\n\n');

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe('export EDITOR=vim\n\nalias g=git\n\n\n');
  });

  test('a user-pasted copy of the marker line above the block does not shadow the real block', () => {
    writeFileSync(zshrc(), '# my note: generated by genie-cli blocks live below\nexport EDITOR=vim\n');
    const original = readFileSync(zshrc(), 'utf-8');
    simulateInstall(zshrc());

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
  });
});

describe('fenced blocks (current install format)', () => {
  /** Install via the real CLI so the file carries the current fenced format. */
  function cliInstall(): void {
    const res = runShortcuts(['shortcuts', 'install'], 'y\ny\n');
    if (res.code !== 0) throw new Error(`install failed: ${res.stderr}`);
  }

  test('install writes a fenced block and removal restores the file byte-for-byte', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    const original = readFileSync(zshrc(), 'utf-8');
    cliInstall();
    expect(readFileSync(zshrc(), 'utf-8')).toContain('>>> genie shortcuts');

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
  });

  test('an edited interior is still removed whole — uninstall is version-proof', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    cliInstall();
    // Simulate a snippet shipped by a DIFFERENT release (or a user edit inside
    // the fence): the interior no longer matches this binary's generator.
    const drifted = readFileSync(zshrc(), 'utf-8').replace('stty -ixon 2>/dev/null', 'stty -ixon # v9 tweak');
    writeFileSync(zshrc(), drifted);

    expect(removeMarkedContent(zshrc(), MARKER)).toBe('removed');
    expect(readFileSync(zshrc(), 'utf-8')).toBe('export EDITOR=vim\n');
  });
});

describe('shortcuts CLI round-trip', () => {
  test('install then uninstall restores rc files byte-for-byte', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\nalias g=git\n');
    const original = readFileSync(zshrc(), 'utf-8');

    const installed = runShortcuts(['shortcuts', 'install'], 'y\ny\n');
    expect(installed.code).toBe(0);
    expect(existsSync(tmuxConf())).toBe(true);
    expect(readFileSync(zshrc(), 'utf-8')).not.toBe(original);

    const uninstalled = runShortcuts(['shortcuts', 'uninstall'], 'y\ny\n');
    expect(uninstalled.code).toBe(0);
    expect(uninstalled.stdout).toContain('✅ Uninstallation complete!');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
    expect(readFileSync(tmuxConf(), 'utf-8')).toBe('');
  });

  test('a second uninstall is a no-op and says so', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    runShortcuts(['shortcuts', 'install'], 'y\ny\n');
    const first = runShortcuts(['shortcuts', 'uninstall'], 'y\ny\n');
    expect(first.stdout).toContain('✅ Uninstallation complete!');
    const zshAfterFirst = readFileSync(zshrc(), 'utf-8');

    const second = runShortcuts(['shortcuts', 'uninstall'], 'y\ny\n');
    expect(second.code).toBe(0);
    expect(second.stdout).toContain('has no genie shortcuts');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(zshAfterFirst);
  });

  test('declining with n leaves files untouched', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    const original = readFileSync(zshrc(), 'utf-8');

    runShortcuts(['shortcuts', 'install'], 'n\nn\n');
    expect(readFileSync(zshrc(), 'utf-8')).toBe(original);
    expect(existsSync(tmuxConf())).toBe(false);
  });

  test('declining with n is a decision, not a failure — exit 0 and a truthful banner', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    const res = runShortcuts(['shortcuts', 'install'], 'n\nn\n');
    expect(res.code).toBe(0);
    // The success banner would be a lie: nothing was installed.
    expect(res.stdout).not.toContain('Installation complete!');
    expect(res.stdout).toContain('every target was declined');
  });
});

/**
 * Dogfood M5 / c2: `genie shortcuts install` ignored `--no-interactive`, drew
 * both prompts, auto-answered them with "Skipped", printed "Installation
 * complete!" and exited 0 having written nothing — so every scripted or CI
 * invocation was a silent success no-op. The contract now has exactly two
 * non-interactive endings: apply the documented default (`--yes`), or exit
 * non-zero with a one-line reason.
 */
describe('shortcuts non-interactive contract (M5)', () => {
  test('--no-interactive refuses on one stderr line, exits 2, and writes nothing', () => {
    const res = runShortcuts(['--no-interactive', 'shortcuts', 'install'], '');
    expect(res.code).toBe(2);
    expect(res.stderr.trim()).toBe(SHORTCUTS_NON_INTERACTIVE_MESSAGE);
    expect(res.stdout).not.toContain('Installation complete!');
    expect(res.stdout).not.toContain('Add shortcuts to'); // no prompt was rendered
    expect(existsSync(tmuxConf())).toBe(false);
    expect(existsSync(zshrc())).toBe(false);
    expect(existsSync(join(dir, '.bashrc'))).toBe(false);
  });

  test('--no-interactive --yes applies the documented default and exits 0', () => {
    const res = runShortcuts(['--no-interactive', 'shortcuts', 'install', '--yes'], '');
    expect(res.code).toBe(0);
    expect(res.stdout).toContain('Installation complete!');
    expect(readFileSync(tmuxConf(), 'utf-8')).toContain('>>> genie shortcuts');
    expect(readFileSync(join(dir, '.bashrc'), 'utf-8')).toContain('>>> genie shortcuts');
  });

  test('EOF on stdin exits 2 with a reason instead of reporting success', () => {
    const res = runShortcuts(['shortcuts', 'install'], '');
    expect(res.code).toBe(2);
    expect(res.stderr.trim()).toBe(SHORTCUTS_UNANSWERED_MESSAGE);
    expect(res.stdout).not.toContain('Installation complete!');
    expect(existsSync(tmuxConf())).toBe(false);
    expect(existsSync(zshrc())).toBe(false);
    expect(existsSync(join(dir, '.bashrc'))).toBe(false);
  });

  test('stdin that runs out mid-run is a failure, not a partial success', () => {
    writeFileSync(zshrc(), 'export EDITOR=vim\n');
    // One answer, two targets: tmux.conf is written, the rc file never gets asked.
    const res = runShortcuts(['shortcuts', 'install'], 'y\n');
    expect(res.code).toBe(2);
    expect(res.stderr.trim()).toBe(SHORTCUTS_UNANSWERED_MESSAGE);
    expect(res.stdout).not.toContain('Installation complete!');
    expect(readFileSync(zshrc(), 'utf-8')).toBe('export EDITOR=vim\n');
  });

  test('uninstall honours the same contract', () => {
    expect(runShortcuts(['--no-interactive', 'shortcuts', 'install', '--yes'], '').code).toBe(0);

    const refused = runShortcuts(['--no-interactive', 'shortcuts', 'uninstall'], '');
    expect(refused.code).toBe(2);
    expect(refused.stderr.trim()).toBe(SHORTCUTS_NON_INTERACTIVE_MESSAGE);
    expect(readFileSync(tmuxConf(), 'utf-8')).toContain('>>> genie shortcuts');

    const applied = runShortcuts(['--no-interactive', 'shortcuts', 'uninstall', '--yes'], '');
    expect(applied.code).toBe(0);
    expect(applied.stdout).toContain('Uninstallation complete!');
    expect(readFileSync(tmuxConf(), 'utf-8')).not.toContain('>>> genie shortcuts');
  });

  test('--yes on a host with nothing to do is still a clean exit 0', () => {
    runShortcuts(['--no-interactive', 'shortcuts', 'install', '--yes'], '');
    const again = runShortcuts(['--no-interactive', 'shortcuts', 'install', '--yes'], '');
    expect(again.code).toBe(0);
    expect(again.stdout).toContain('already has genie shortcuts');
  });
});
