import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import * as readline from 'node:readline';

// Generate tmux.conf snippet for Warp-like shortcuts
function generateTmuxConfig(): string {
  return `# Warp-like keyboard shortcuts (generated by genie-cli)
# To use: add to ~/.tmux.conf or source this file

# Ctrl+T: New window (tab) in current session
bind-key -n C-t new-window -c "#{pane_current_path}"

# Ctrl+S: Vertical split (requires stty -ixon in shell rc)
bind-key -n C-s split-window -v -c "#{pane_current_path}"

# Ctrl+Shift+S: Horizontal split
bind-key -n C-S split-window -h -c "#{pane_current_path}"
`;
}

// Generate termux.properties snippet for extra keys
function generateTermuxConfig(): string {
  return `# Warp-like extra keys (generated by genie-cli)
# To use: add to ~/.termux/termux.properties

# Extra keys row with F-keys for shortcuts
# F1=New Tab, F2=VSplit, F3=HSplit
extra-keys = [['ESC','TAB','CTRL','ALT','F1','F2','F3']]
`;
}

// Generate shell functions for bashrc/zshrc
function generateShellFunctions(): string {
  return `# Warp-like shortcuts (generated by genie-cli)
# To use: add to ~/.bashrc or ~/.zshrc

# Disable Ctrl+S flow control (required for Ctrl+S to work in tmux)
stty -ixon 2>/dev/null

# Genie shortcuts (for Termux extra keys F1-F3)
genie-new-tab() {
  local session
  session=$(tmux display-message -p '#S' 2>/dev/null)
  if [ -n "$session" ]; then
    tmux new-window -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-vsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -v -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-hsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -h -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

# Bind F1-F3 to genie shortcuts (works in Termux)
bind -x '"\eOP":"genie-new-tab"' 2>/dev/null   # F1
bind -x '"\eOQ":"genie-vsplit"' 2>/dev/null    # F2
bind -x '"\eOR":"genie-hsplit"' 2>/dev/null    # F3
`;
}

// Display all shortcuts in a readable format
export function displayShortcuts(): void {
  console.log(`
Warp-like Terminal Shortcuts for tmux + Termux

┌──────────────────┬────────────────────────────────────────┐
│ Shortcut         │ Action                                 │
├──────────────────┼────────────────────────────────────────┤
│ Ctrl+T           │ New tab (window) in current session    │
│ Ctrl+S           │ Vertical split in current session      │
│ Ctrl+Shift+S     │ Horizontal split in current session    │
└──────────────────┴────────────────────────────────────────┘

Termux Extra Keys (F1-F3):
  F1 → New tab       F2 → Vertical split
  F3 → Horizontal split

Commands:
  genie shortcuts show       Show available shortcuts and installation status
  genie shortcuts install    Install to config files (~/.tmux.conf, shell rc)
  genie shortcuts uninstall  Remove installed shortcuts
`);
}

// One readline interface per process with a persistent `line` listener.
// Piped answers must never be lost (a one-shot question listener drops lines
// that arrive before the next prompt is asked) and a closed stdin must not
// hang the installer: EOF declines any pending prompt.
let promptRl: readline.Interface | null = null;
let promptEof = false;
const queuedAnswers: string[] = [];
let pendingPrompt: ((answer: string) => void) | null = null;

function ensurePromptRl(): readline.Interface {
  if (promptRl) return promptRl;
  promptRl = readline.createInterface({ input: process.stdin, output: process.stdout });
  promptRl.on('line', (line) => {
    const answer = line.trim().toLowerCase();
    if (pendingPrompt) {
      const resolve = pendingPrompt;
      pendingPrompt = null;
      resolve(answer);
    } else {
      queuedAnswers.push(answer);
    }
  });
  promptRl.on('close', () => {
    promptEof = true;
    if (pendingPrompt) {
      const resolve = pendingPrompt;
      pendingPrompt = null;
      resolve('n');
    }
  });
  return promptRl;
}

// Helper to prompt user.
async function prompt(question: string): Promise<string> {
  ensurePromptRl();
  process.stdout.write(question);
  if (promptEof) return 'n';
  const queued = queuedAnswers.shift();
  if (queued !== undefined) return queued;
  return new Promise((resolve) => {
    pendingPrompt = resolve;
  });
}

// Check if content already exists in file
function contentExists(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, 'utf-8');
  return content.includes(marker);
}

/**
 * Prompt to install config content to a file. Skips if marker already present.
 */
async function promptInstallTo(
  filePath: string,
  marker: string,
  label: string,
  contentFn: () => string,
  ensureDir?: string,
): Promise<void> {
  if (contentExists(filePath, marker)) {
    console.log(`✓ ${label} already has genie shortcuts`);
    return;
  }
  const answer = await prompt(`Add shortcuts to ${filePath}? [Y/n] `);
  if (answer === 'n') {
    console.log(`⏭️ Skipped ${label}`);
    return;
  }
  if (ensureDir && !existsSync(ensureDir)) {
    mkdirSync(ensureDir, { recursive: true });
  }
  appendFileSync(filePath, `\n${contentFn()}`);
  console.log(`✅ Added to ${filePath}`);
}

// Install shortcuts to config files
export async function installShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Installing Warp-like shortcuts...\n');

  await promptInstallTo(join(home, '.tmux.conf'), marker, 'tmux.conf', generateTmuxConfig);

  const shellRc = existsSync(join(home, '.zshrc')) ? join(home, '.zshrc') : join(home, '.bashrc');
  await promptInstallTo(shellRc, marker, shellRc, generateShellFunctions);

  const termuxDir = join(home, '.termux');
  const termuxProps = join(termuxDir, 'termux.properties');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    await promptInstallTo(termuxProps, marker, 'termux.properties', generateTermuxConfig, termuxDir);
    if (contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  console.log('\n✅ Installation complete!');
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}

// Check if shortcuts are installed in a file
export function isShortcutsInstalled(filePath: string): boolean {
  const marker = 'generated by genie-cli';
  return contentExists(filePath, marker);
}

/**
 * The exact line sequence `install` appends for this file's snippet, or null
 * for files genie never installs to. Uninstall removes exactly these lines —
 * never a heuristic superset — so user-owned lines that merely contain words
 * like `genie` or `stty -ixon` are never touched.
 */
export function expectedSnippetLines(filePath: string): string[] | null {
  const base = filePath.split(/[\\/]/).pop() ?? '';
  if (base === '.tmux.conf') return generateTmuxConfig().split('\n');
  if (base === 'termux.properties') return generateTermuxConfig().split('\n');
  if (base === '.zshrc' || base === '.bashrc') return generateShellFunctions().split('\n');
  return null;
}

/**
 * Remove the installed snippet from a file. Returns:
 *  - `'removed'` — the exact installed block was found and removed,
 *  - `'absent'` — no marker, or not a genie-managed file,
 *  - `'modified'` — the block differs from what `install` wrote (edited since),
 *    so nothing is deleted; the user removes it manually.
 */
export function removeMarkedContent(filePath: string, marker: string): 'removed' | 'absent' | 'modified' {
  if (!existsSync(filePath)) return 'absent';
  const content = readFileSync(filePath, 'utf-8');
  if (!content.includes(marker)) return 'absent';
  const expected = expectedSnippetLines(filePath);
  if (expected === null) return 'absent';

  const lines = content.split('\n');
  const markerIdx = lines.findIndex((line) => line.includes(marker));
  if (markerIdx === -1) return 'absent';

  // The snippet ends with a newline, so `split('\n')` yields a trailing ''
  // element; the file only shows that '' when the block is the file's last
  // content. Drop it so user content directly after the block still matches.
  if (expected[expected.length - 1] === '') expected.pop();

  const block = lines.slice(markerIdx, markerIdx + expected.length);
  if (block.length !== expected.length || block.some((line, i) => line !== expected[i])) {
    return 'modified';
  }

  // `install` appends `\n${snippet}`; the prepended blank line belongs to the
  // block, not the user — drop it when the file had content before the block.
  let start = markerIdx;
  if (lines[start - 1] === '') start -= 1;

  const kept = [...lines.slice(0, start), ...lines.slice(markerIdx + expected.length)];
  while (kept.length > 0 && kept[kept.length - 1] === '') kept.pop();
  const newContent = kept.length > 0 ? `${kept.join('\n')}\n` : '';
  writeFileSync(filePath, newContent);
  return 'removed';
}

/**
 * Prompt to uninstall config content from a file. Returns true when a block
 * was found but left in place (edited since install).
 */
async function promptUninstallFrom(filePath: string, marker: string, label: string): Promise<boolean> {
  if (!existsSync(filePath)) return false;
  if (!contentExists(filePath, marker)) {
    console.log(`✓ ${label} has no genie shortcuts`);
    return false;
  }
  const answer = await prompt(`Remove shortcuts from ${filePath}? [Y/n] `);
  if (answer === 'n') {
    console.log(`⏭️ Skipped ${label}`);
    return false;
  }
  const result = removeMarkedContent(filePath, marker);
  if (result === 'removed') {
    console.log(`✅ Removed from ${filePath}`);
    return false;
  }
  if (result === 'modified') {
    console.log(`⚠️ ${label} block was edited after install — left untouched, remove it manually`);
    return true;
  }
  return false;
}

// Uninstall shortcuts from config files
export async function uninstallShortcuts(): Promise<void> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Uninstalling Warp-like shortcuts...\n');

  let leftUntouched = false;
  leftUntouched = (await promptUninstallFrom(join(home, '.tmux.conf'), marker, 'tmux.conf')) || leftUntouched;

  for (const shellRc of [join(home, '.zshrc'), join(home, '.bashrc')]) {
    leftUntouched = (await promptUninstallFrom(shellRc, marker, shellRc)) || leftUntouched;
  }

  const termuxDir = join(home, '.termux');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    const termuxProps = join(termuxDir, 'termux.properties');
    leftUntouched = (await promptUninstallFrom(termuxProps, marker, 'termux.properties')) || leftUntouched;
    if (!contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  console.log(
    leftUntouched
      ? '\n⚠️ Uninstallation incomplete — edited blocks were left in place.'
      : '\n✅ Uninstallation complete!',
  );
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
}
