import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import * as readline from 'node:readline';

// Generate tmux.conf snippet for Warp-like shortcuts
function generateTmuxConfig(): string {
  return `# Warp-like keyboard shortcuts (generated by genie-cli)
# To use: add to ~/.tmux.conf or source this file

# Ctrl+T: New window (tab) in current session
bind-key -n C-t new-window -c "#{pane_current_path}"

# Ctrl+S: Vertical split (requires stty -ixon in shell rc)
bind-key -n C-s split-window -v -c "#{pane_current_path}"

# Ctrl+Shift+S: Horizontal split
bind-key -n C-S split-window -h -c "#{pane_current_path}"
`;
}

// Generate termux.properties snippet for extra keys
function generateTermuxConfig(): string {
  return `# Warp-like extra keys (generated by genie-cli)
# To use: add to ~/.termux/termux.properties

# Extra keys row with F-keys for shortcuts
# F1=New Tab, F2=VSplit, F3=HSplit
extra-keys = [['ESC','TAB','CTRL','ALT','F1','F2','F3']]
`;
}

// Generate shell functions for bashrc/zshrc
function generateShellFunctions(): string {
  return `# Warp-like shortcuts (generated by genie-cli)
# To use: add to ~/.bashrc or ~/.zshrc

# Disable Ctrl+S flow control (required for Ctrl+S to work in tmux)
stty -ixon 2>/dev/null

# Genie shortcuts (for Termux extra keys F1-F3)
genie-new-tab() {
  local session
  session=$(tmux display-message -p '#S' 2>/dev/null)
  if [ -n "$session" ]; then
    tmux new-window -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-vsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -v -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

genie-hsplit() {
  if tmux display-message -p '#S' >/dev/null 2>&1; then
    tmux split-window -h -c "#{pane_current_path}"
  else
    echo "Not in a tmux session"
  fi
}

# Bind F1-F3 to genie shortcuts (works in Termux)
bind -x '"\eOP":"genie-new-tab"' 2>/dev/null   # F1
bind -x '"\eOQ":"genie-vsplit"' 2>/dev/null    # F2
bind -x '"\eOR":"genie-hsplit"' 2>/dev/null    # F3
`;
}

// Display all shortcuts in a readable format
export function displayShortcuts(): void {
  console.log(`
Warp-like Terminal Shortcuts for tmux + Termux

┌──────────────────┬────────────────────────────────────────┐
│ Shortcut         │ Action                                 │
├──────────────────┼────────────────────────────────────────┤
│ Ctrl+T           │ New tab (window) in current session    │
│ Ctrl+S           │ Vertical split in current session      │
│ Ctrl+Shift+S     │ Horizontal split in current session    │
└──────────────────┴────────────────────────────────────────┘

Termux Extra Keys (F1-F3):
  F1 → New tab       F2 → Vertical split
  F3 → Horizontal split

Commands:
  genie shortcuts show       Show available shortcuts and installation status
  genie shortcuts install    Install to config files (~/.tmux.conf, shell rc)
  genie shortcuts uninstall  Remove installed shortcuts
`);
}

// One readline interface per process with a persistent `line` listener.
// Piped answers must never be lost (a one-shot question listener drops lines
// that arrive before the next prompt is asked) and a closed stdin must not
// hang the installer: EOF resolves any pending prompt with NO_ANSWER.
//
// NO_ANSWER is deliberately distinct from the answer `n`. Before 2026-09-15 a
// closed stdin was read as "the user declined every target", so a scripted
// `genie shortcuts install` skipped both files, printed "Installation
// complete!" and exited 0 — a silent success no-op (dogfood M5/c2). A decline
// is a decision and still exits 0; an unanswered prompt is a failure.
const NO_ANSWER = Symbol('no-answer');
type PromptAnswer = string | typeof NO_ANSWER;

let promptRl: readline.Interface | null = null;
let promptEof = false;
const queuedAnswers: string[] = [];
let pendingPrompt: ((answer: PromptAnswer) => void) | null = null;

function ensurePromptRl(): readline.Interface {
  if (promptRl) return promptRl;
  promptRl = readline.createInterface({ input: process.stdin, output: process.stdout });
  promptRl.on('line', (line) => {
    const answer = line.trim().toLowerCase();
    if (pendingPrompt) {
      const resolve = pendingPrompt;
      pendingPrompt = null;
      resolve(answer);
    } else {
      queuedAnswers.push(answer);
    }
  });
  promptRl.on('close', () => {
    promptEof = true;
    if (pendingPrompt) {
      const resolve = pendingPrompt;
      pendingPrompt = null;
      resolve(NO_ANSWER);
    }
  });
  return promptRl;
}

/**
 * Release the shared readline interface once a command's prompts are done. The
 * interface refs stdin, so on an interactive TTY (where EOF never arrives) a
 * command that leaves it open completes its work and then hangs the process.
 * Listeners are detached before closing so the explicit close is not recorded
 * as stdin EOF — a later command in the same process gets a fresh interface.
 */
function closePromptRl(): void {
  if (!promptRl) return;
  promptRl.removeAllListeners('line');
  promptRl.removeAllListeners('close');
  promptRl.close();
  promptRl = null;
}

// Helper to prompt user. Resolves to NO_ANSWER when stdin is already at EOF
// (or reaches it while the question is pending) with nothing queued.
async function prompt(question: string): Promise<PromptAnswer> {
  ensurePromptRl();
  const queued = queuedAnswers.shift();
  if (queued !== undefined) {
    process.stdout.write(question);
    return queued;
  }
  if (promptEof) return NO_ANSWER;
  process.stdout.write(question);
  return new Promise((resolve) => {
    pendingPrompt = resolve;
  });
}

/**
 * Fence lines wrapping every installed snippet. Uninstall removes the whole
 * fenced region regardless of interior edits (the begin line says exactly
 * that), so a future release can change a snippet without stranding existing
 * installs behind a byte-exact match. Blocks written by pre-fence releases are
 * removed by the exact-snippet legacy lane in {@link removeMarkedContent}.
 * The begin line contains the install marker (`generated by genie-cli`), so
 * presence checks see fenced and legacy blocks alike.
 */
const FENCE_BEGIN =
  '# >>> genie shortcuts — managed block, `genie shortcuts uninstall` removes it whole (generated by genie-cli) >>>';
const FENCE_END = '# <<< genie shortcuts <<<';

// Check if content already exists in file
function contentExists(filePath: string, marker: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, 'utf-8');
  return content.includes(marker);
}

/**
 * What happened to one target.
 *  - `applied`     — written (or already present, which is the same end state)
 *  - `declined`    — the user answered `n`; a decision, not a failure
 *  - `unanswered`  — stdin had no answer to give (EOF / closed / exhausted)
 */
type TargetOutcome = 'applied' | 'declined' | 'unanswered';

/**
 * Prompt to install config content to a file. Skips if marker already present.
 */
async function promptInstallTo(
  filePath: string,
  marker: string,
  label: string,
  contentFn: () => string,
  options: { autoYes: boolean; ensureDir?: string },
): Promise<TargetOutcome> {
  if (contentExists(filePath, marker)) {
    console.log(`✓ ${label} already has genie shortcuts`);
    return 'applied';
  }
  if (!options.autoYes) {
    const answer = await prompt(`Add shortcuts to ${filePath}? [Y/n] `);
    if (answer === NO_ANSWER) {
      console.log(`⏭️ Skipped ${label} — no answer on stdin`);
      return 'unanswered';
    }
    if (answer === 'n') {
      console.log(`⏭️ Skipped ${label}`);
      return 'declined';
    }
  }
  if (options.ensureDir && !existsSync(options.ensureDir)) {
    mkdirSync(options.ensureDir, { recursive: true });
  }
  appendFileSync(filePath, `\n${FENCE_BEGIN}\n${contentFn()}${FENCE_END}\n`);
  console.log(`✅ Added to ${filePath}`);
  return 'applied';
}

/**
 * How a `shortcuts` run ended. `unanswered` is the non-zero case: prompts were
 * asked and stdin had nothing to answer them with, so nothing was written and
 * the success banner would be a lie.
 */
export type ShortcutsOutcome = 'applied' | 'declined' | 'unanswered' | 'refused';

export interface ShortcutsRunOptions {
  /**
   * Apply the documented default — accept every target — without prompting.
   * This is the non-interactive route (`genie shortcuts install --yes`).
   */
  yes?: boolean;
  /**
   * Whether this process may render a prompt at all. `false` (global
   * `--no-interactive`, `CI`, or a non-TTY) without `yes` is `refused`: one
   * line, exit 2, nothing written.
   */
  canPrompt?: boolean;
}

/** The one line a prompt-less run with no `--yes` gets, on stderr, before exit 2. */
export const SHORTCUTS_NON_INTERACTIVE_MESSAGE =
  'genie shortcuts needs an answer for each target. Re-run with --yes to accept the defaults, or drop --no-interactive.';

/** The one line a run whose prompts outran stdin gets, on stderr, before exit 2. */
export const SHORTCUTS_UNANSWERED_MESSAGE =
  'genie shortcuts: stdin ended before every target was answered — nothing was written. Re-run with --yes to accept the defaults.';

/**
 * Collapse per-target outcomes into the run's outcome. `unanswered` dominates
 * (a partially-answered run is a failed run); otherwise a run in which the user
 * declined everything is `declined` — deliberate, and still exit 0.
 */
function summarize(outcomes: TargetOutcome[]): ShortcutsOutcome {
  if (outcomes.includes('unanswered')) return 'unanswered';
  if (outcomes.length > 0 && outcomes.every((outcome) => outcome === 'declined')) return 'declined';
  return 'applied';
}

// Install shortcuts to config files
export async function installShortcuts(options: ShortcutsRunOptions = {}): Promise<ShortcutsOutcome> {
  if (!options.yes && options.canPrompt === false) {
    console.error(SHORTCUTS_NON_INTERACTIVE_MESSAGE);
    return 'refused';
  }
  try {
    return await runInstallShortcuts(options.yes === true);
  } finally {
    closePromptRl();
  }
}

async function runInstallShortcuts(autoYes: boolean): Promise<ShortcutsOutcome> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Installing Warp-like shortcuts...\n');

  const outcomes: TargetOutcome[] = [];
  outcomes.push(await promptInstallTo(join(home, '.tmux.conf'), marker, 'tmux.conf', generateTmuxConfig, { autoYes }));

  const shellRc = existsSync(join(home, '.zshrc')) ? join(home, '.zshrc') : join(home, '.bashrc');
  outcomes.push(await promptInstallTo(shellRc, marker, shellRc, generateShellFunctions, { autoYes }));

  const termuxDir = join(home, '.termux');
  const termuxProps = join(termuxDir, 'termux.properties');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    outcomes.push(
      await promptInstallTo(termuxProps, marker, 'termux.properties', generateTermuxConfig, {
        autoYes,
        ensureDir: termuxDir,
      }),
    );
    if (contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  const outcome = summarize(outcomes);
  if (outcome === 'unanswered') {
    console.error(SHORTCUTS_UNANSWERED_MESSAGE);
    return outcome;
  }
  console.log(
    outcome === 'declined' ? '\n⏭️ Nothing installed — every target was declined.' : '\n✅ Installation complete!',
  );
  if (outcome === 'declined') return outcome;
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
  return outcome;
}

// Check if shortcuts are installed in a file
export function isShortcutsInstalled(filePath: string): boolean {
  const marker = 'generated by genie-cli';
  return contentExists(filePath, marker);
}

/**
 * The exact INTERIOR line sequence pre-fence releases appended for this file's
 * snippet, or null for files genie never installs to. This is the legacy
 * uninstall lane: a block with no fence lines is removed only when it matches
 * these lines exactly — never a heuristic superset — so user-owned lines that
 * merely contain words like `genie` or `stty -ixon` are never touched. Do not
 * edit the generate* snippets without preserving what the last pre-fence
 * release shipped, or legacy installs become unremovable.
 */
export function expectedSnippetLines(filePath: string): string[] | null {
  const base = filePath.split(/[\\/]/).pop() ?? '';
  if (base === '.tmux.conf') return generateTmuxConfig().split('\n');
  if (base === 'termux.properties') return generateTermuxConfig().split('\n');
  if (base === '.zshrc' || base === '.bashrc') return generateShellFunctions().split('\n');
  return null;
}

/**
 * Remove the installed snippet from a file. Returns:
 *  - `'removed'` — a fenced block was removed whole, or a legacy (pre-fence)
 *    block matched its release's exact lines and was removed,
 *  - `'absent'` — no marker, or not a genie-managed file,
 *  - `'modified'` — a legacy block differs from what its `install` wrote
 *    (edited since), so nothing is deleted; the user removes it manually.
 */
export function removeMarkedContent(filePath: string, marker: string): 'removed' | 'absent' | 'modified' {
  if (!existsSync(filePath)) return 'absent';
  const content = readFileSync(filePath, 'utf-8');
  if (!content.includes(marker)) return 'absent';
  if (expectedSnippetLines(filePath) === null) return 'absent';

  const lines = content.split('\n');
  // Fenced lane: remove everything between the fences, whatever it now says —
  // the begin line warns the block is managed. Version-proof by construction.
  const begin = lines.indexOf(FENCE_BEGIN);
  if (begin !== -1) {
    const end = lines.indexOf(FENCE_END, begin + 1);
    if (end !== -1) return spliceOutBlock(filePath, lines, begin, end + 1);
  }
  return removeLegacySnippet(filePath, lines, marker);
}

/** Legacy lane: exact-match the pre-fence snippet at EVERY marker occurrence. */
function removeLegacySnippet(filePath: string, lines: string[], marker: string): 'removed' | 'modified' {
  const expected = expectedSnippetLines(filePath) as string[];
  // The snippet ends with a newline, so `split('\n')` yields a trailing ''
  // element; the file only shows that '' when the block is the file's last
  // content. Drop it so user content directly after the block still matches.
  if (expected[expected.length - 1] === '') expected.pop();

  // A user-pasted copy of the header line must not shadow the real block: try
  // every line carrying the marker, remove the first that matches exactly.
  for (let idx = 0; idx < lines.length; idx++) {
    if (!lines[idx].includes(marker)) continue;
    const block = lines.slice(idx, idx + expected.length);
    if (block.length === expected.length && block.every((line, i) => line === expected[i])) {
      return spliceOutBlock(filePath, lines, idx, idx + expected.length);
    }
  }
  return 'modified';
}

/** Write the file back without lines [blockStart, blockEnd) and the blank line `install` prepended. */
function spliceOutBlock(filePath: string, lines: string[], blockStart: number, blockEnd: number): 'removed' {
  // `install` appends `\n${snippet}`; the prepended blank line belongs to the
  // block, not the user — drop it when the file had content before the block.
  let start = blockStart;
  if (lines[start - 1] === '') start -= 1;

  const kept = [...lines.slice(0, start), ...lines.slice(blockEnd)];
  // A single trailing '' is `split('\n')`'s artifact of the file's final
  // newline — drop exactly that one. Deeper trailing blank lines are
  // user-owned content and must survive the uninstall.
  if (kept[kept.length - 1] === '') kept.pop();
  const newContent = kept.length > 0 ? `${kept.join('\n')}\n` : '';
  writeFileSync(filePath, newContent);
  return 'removed';
}

interface UninstallTargetResult {
  outcome: TargetOutcome;
  /** A managed block was found but left in place (edited since install). */
  leftUntouched: boolean;
}

/** Prompt to uninstall config content from a file. */
async function promptUninstallFrom(
  filePath: string,
  marker: string,
  label: string,
  autoYes: boolean,
): Promise<UninstallTargetResult> {
  if (!existsSync(filePath)) return { outcome: 'applied', leftUntouched: false };
  if (!contentExists(filePath, marker)) {
    console.log(`✓ ${label} has no genie shortcuts`);
    return { outcome: 'applied', leftUntouched: false };
  }
  if (!autoYes) {
    const answer = await prompt(`Remove shortcuts from ${filePath}? [Y/n] `);
    if (answer === NO_ANSWER) {
      console.log(`⏭️ Skipped ${label} — no answer on stdin`);
      return { outcome: 'unanswered', leftUntouched: false };
    }
    if (answer === 'n') {
      console.log(`⏭️ Skipped ${label}`);
      return { outcome: 'declined', leftUntouched: false };
    }
  }
  const result = removeMarkedContent(filePath, marker);
  if (result === 'removed') {
    console.log(`✅ Removed from ${filePath}`);
    return { outcome: 'applied', leftUntouched: false };
  }
  if (result === 'modified') {
    console.log(`⚠️ ${label} block was edited after install — left untouched, remove it manually`);
    return { outcome: 'applied', leftUntouched: true };
  }
  return { outcome: 'applied', leftUntouched: false };
}

// Uninstall shortcuts from config files
export async function uninstallShortcuts(options: ShortcutsRunOptions = {}): Promise<ShortcutsOutcome> {
  if (!options.yes && options.canPrompt === false) {
    console.error(SHORTCUTS_NON_INTERACTIVE_MESSAGE);
    return 'refused';
  }
  try {
    return await runUninstallShortcuts(options.yes === true);
  } finally {
    closePromptRl();
  }
}

async function runUninstallShortcuts(autoYes: boolean): Promise<ShortcutsOutcome> {
  const home = homedir();
  const marker = 'generated by genie-cli';

  console.log('Uninstalling Warp-like shortcuts...\n');

  const outcomes: TargetOutcome[] = [];
  let leftUntouched = false;
  const record = (result: UninstallTargetResult): void => {
    outcomes.push(result.outcome);
    leftUntouched = result.leftUntouched || leftUntouched;
  };

  record(await promptUninstallFrom(join(home, '.tmux.conf'), marker, 'tmux.conf', autoYes));

  for (const shellRc of [join(home, '.zshrc'), join(home, '.bashrc')]) {
    record(await promptUninstallFrom(shellRc, marker, shellRc, autoYes));
  }

  const termuxDir = join(home, '.termux');
  const isTermux = existsSync(termuxDir) || process.env.TERMUX_VERSION;

  if (isTermux) {
    const termuxProps = join(termuxDir, 'termux.properties');
    record(await promptUninstallFrom(termuxProps, marker, 'termux.properties', autoYes));
    if (!contentExists(termuxProps, marker)) {
      console.log('   Run: termux-reload-settings');
    }
  }

  const outcome = summarize(outcomes);
  if (outcome === 'unanswered') {
    console.error(SHORTCUTS_UNANSWERED_MESSAGE);
    return outcome;
  }
  console.log(
    leftUntouched
      ? '\n⚠️ Uninstallation incomplete — edited blocks were left in place.'
      : '\n✅ Uninstallation complete!',
  );
  console.log('\nNext steps:');
  console.log('  1. Reload tmux: tmux source ~/.tmux.conf');
  console.log('  2. Restart your shell or run: source ~/.bashrc');
  if (isTermux) {
    console.log('  3. Reload Termux: termux-reload-settings');
  }
  return outcome;
}
